// ============================================================
// AŞAMA 3: İNŞA — 6 Takım × 5 Ajan = 30 Birim
// ============================================================
const { ASAMALAR } = require('./types');
const A = ASAMALAR.INSA;

const INSA = [

  // ── TS: TEKNOLOJİ SEÇİMİ ───────────────────────────────────
  { id: 'TS-01', kod_adi: 'TEKNOLOJİ-ALFA', takim_kodu: 'TS', asama: A, uzmanlik_alani: 'Teknoloji Seçimi',
    gorev_tanimi: 'Hangi dil, framework, veritabanı, araç kullanılacak — alternatifleriyle karşılaştırır',
    beceriler: ['programlama_dilleri', 'framework_karsilastirma', 'veritabani_secimi', 'arac_degerlendirme', 'benchmark', 'teknoloji_kiyaslama', 'ekosistem_analizi', 'uyumluluk_kontrolu'],
    kapsam_siniri: ['test', 'deployment', 'ui_ux', 'hukuk', 'maliyet', 'izleme', 'dokumantasyon', 'egitim'],
    durum: 'HAZIR', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'TS-02', kod_adi: 'TEKNOLOJİ-BRAVO', takim_kodu: 'TS', asama: A, uzmanlik_alani: 'Teknoloji Seçimi',
    gorev_tanimi: 'Hangi dil, framework, veritabanı, araç kullanılacak — alternatifleriyle karşılaştırır',
    beceriler: ['programlama_dilleri', 'framework_karsilastirma', 'veritabani_secimi', 'arac_degerlendirme', 'benchmark', 'teknoloji_kiyaslama', 'ekosistem_analizi', 'uyumluluk_kontrolu'],
    kapsam_siniri: ['test', 'deployment', 'ui_ux', 'hukuk', 'maliyet', 'izleme', 'dokumantasyon', 'egitim'],
    durum: 'HAZIR', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'TS-03', kod_adi: 'TEKNOLOJİ-CHARLIE', takim_kodu: 'TS', asama: A, uzmanlik_alani: 'Teknoloji Seçimi',
    gorev_tanimi: 'Hangi dil, framework, veritabanı, araç kullanılacak — alternatifleriyle karşılaştırır',
    beceriler: ['programlama_dilleri', 'framework_karsilastirma', 'veritabani_secimi', 'arac_degerlendirme', 'benchmark', 'teknoloji_kiyaslama', 'ekosistem_analizi', 'uyumluluk_kontrolu'],
    kapsam_siniri: ['test', 'deployment', 'ui_ux', 'hukuk', 'maliyet', 'izleme', 'dokumantasyon', 'egitim'],
    durum: 'HAZIR', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'TS-04', kod_adi: 'TEKNOLOJİ-DELTA', takim_kodu: 'TS', asama: A, uzmanlik_alani: 'Teknoloji Seçimi',
    gorev_tanimi: 'Hangi dil, framework, veritabanı, araç kullanılacak — alternatifleriyle karşılaştırır',
    beceriler: ['programlama_dilleri', 'framework_karsilastirma', 'veritabani_secimi', 'arac_degerlendirme', 'benchmark', 'teknoloji_kiyaslama', 'ekosistem_analizi', 'uyumluluk_kontrolu'],
    kapsam_siniri: ['test', 'deployment', 'ui_ux', 'hukuk', 'maliyet', 'izleme', 'dokumantasyon', 'egitim'],
    durum: 'HAZIR', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'TS-05', kod_adi: 'TEKNOLOJİ-ECHO', takim_kodu: 'TS', asama: A, uzmanlik_alani: 'Teknoloji Seçimi',
    gorev_tanimi: 'Hangi dil, framework, veritabanı, araç kullanılacak — alternatifleriyle karşılaştırır',
    beceriler: ['programlama_dilleri', 'framework_karsilastirma', 'veritabani_secimi', 'arac_degerlendirme', 'benchmark', 'teknoloji_kiyaslama', 'ekosistem_analizi', 'uyumluluk_kontrolu'],
    kapsam_siniri: ['test', 'deployment', 'ui_ux', 'hukuk', 'maliyet', 'izleme', 'dokumantasyon', 'egitim'],
    durum: 'HAZIR', tamamlanan_gorev: 0, hata_sayisi: 0 },

  // ── KK: KOD KALİTESİ VE STANDARTLAR ────────────────────────
  { id: 'KK-01', kod_adi: 'KODKALİTE-ALFA', takim_kodu: 'KK', asama: A, uzmanlik_alani: 'Kod Kalitesi ve Standartlar',
    gorev_tanimi: 'Temiz, okunabilir, bakımı kolay kod yazılmasını denetler',
    beceriler: ['kod_standartlari', 'linting', 'code_review', 'tasarim_kaliplari', 'refactoring', 'clean_code', 'solid', 'okunabilirlik'],
    kapsam_siniri: ['deployment', 'ui_ux', 'hukuk', 'maliyet', 'izleme', 'veritabani_tasarimi', 'egitim', 'gereksinim'],
    durum: 'HAZIR', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'KK-02', kod_adi: 'KODKALİTE-BRAVO', takim_kodu: 'KK', asama: A, uzmanlik_alani: 'Kod Kalitesi ve Standartlar',
    gorev_tanimi: 'Temiz, okunabilir, bakımı kolay kod yazılmasını denetler',
    beceriler: ['kod_standartlari', 'linting', 'code_review', 'tasarim_kaliplari', 'refactoring', 'clean_code', 'solid', 'okunabilirlik'],
    kapsam_siniri: ['deployment', 'ui_ux', 'hukuk', 'maliyet', 'izleme', 'veritabani_tasarimi', 'egitim', 'gereksinim'],
    durum: 'HAZIR', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'KK-03', kod_adi: 'KODKALİTE-CHARLIE', takim_kodu: 'KK', asama: A, uzmanlik_alani: 'Kod Kalitesi ve Standartlar',
    gorev_tanimi: 'Temiz, okunabilir, bakımı kolay kod yazılmasını denetler',
    beceriler: ['kod_standartlari', 'linting', 'code_review', 'tasarim_kaliplari', 'refactoring', 'clean_code', 'solid', 'okunabilirlik'],
    kapsam_siniri: ['deployment', 'ui_ux', 'hukuk', 'maliyet', 'izleme', 'veritabani_tasarimi', 'egitim', 'gereksinim'],
    durum: 'HAZIR', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'KK-04', kod_adi: 'KODKALİTE-DELTA', takim_kodu: 'KK', asama: A, uzmanlik_alani: 'Kod Kalitesi ve Standartlar',
    gorev_tanimi: 'Temiz, okunabilir, bakımı kolay kod yazılmasını denetler',
    beceriler: ['kod_standartlari', 'linting', 'code_review', 'tasarim_kaliplari', 'refactoring', 'clean_code', 'solid', 'okunabilirlik'],
    kapsam_siniri: ['deployment', 'ui_ux', 'hukuk', 'maliyet', 'izleme', 'veritabani_tasarimi', 'egitim', 'gereksinim'],
    durum: 'HAZIR', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'KK-05', kod_adi: 'KODKALİTE-ECHO', takim_kodu: 'KK', asama: A, uzmanlik_alani: 'Kod Kalitesi ve Standartlar',
    gorev_tanimi: 'Temiz, okunabilir, bakımı kolay kod yazılmasını denetler',
    beceriler: ['kod_standartlari', 'linting', 'code_review', 'tasarim_kaliplari', 'refactoring', 'clean_code', 'solid', 'okunabilirlik'],
    kapsam_siniri: ['deployment', 'ui_ux', 'hukuk', 'maliyet', 'izleme', 'veritabani_tasarimi', 'egitim', 'gereksinim'],
    durum: 'HAZIR', tamamlanan_gorev: 0, hata_sayisi: 0 },

  // ── HY: HATA YÖNETİMİ VE KURTARMA ─────────────────────────
  { id: 'HY-01', kod_adi: 'HATAYÖN-ALFA', takim_kodu: 'HY', asama: A, uzmanlik_alani: 'Hata Yönetimi ve Kurtarma',
    gorev_tanimi: 'Kod içinde hataları yakalayıp sistemin çökmesini önleyen mekanizmaları tasarlar',
    beceriler: ['try_catch', 'graceful_degradation', 'circuit_breaker', 'fallback', 'hata_yakalama', 'hata_siniflandirma', 'retry_mekanizmasi', 'hata_loglama'],
    kapsam_siniri: ['ui_ux', 'deployment', 'hukuk', 'maliyet', 'izleme', 'veritabani_tasarimi', 'egitim', 'gereksinim'],
    durum: 'HAZIR', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'HY-02', kod_adi: 'HATAYÖN-BRAVO', takim_kodu: 'HY', asama: A, uzmanlik_alani: 'Hata Yönetimi ve Kurtarma',
    gorev_tanimi: 'Kod içinde hataları yakalayıp sistemin çökmesini önleyen mekanizmaları tasarlar',
    beceriler: ['try_catch', 'graceful_degradation', 'circuit_breaker', 'fallback', 'hata_yakalama', 'hata_siniflandirma', 'retry_mekanizmasi', 'hata_loglama'],
    kapsam_siniri: ['ui_ux', 'deployment', 'hukuk', 'maliyet', 'izleme', 'veritabani_tasarimi', 'egitim', 'gereksinim'],
    durum: 'HAZIR', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'HY-03', kod_adi: 'HATAYÖN-CHARLIE', takim_kodu: 'HY', asama: A, uzmanlik_alani: 'Hata Yönetimi ve Kurtarma',
    gorev_tanimi: 'Kod içinde hataları yakalayıp sistemin çökmesini önleyen mekanizmaları tasarlar',
    beceriler: ['try_catch', 'graceful_degradation', 'circuit_breaker', 'fallback', 'hata_yakalama', 'hata_siniflandirma', 'retry_mekanizmasi', 'hata_loglama'],
    kapsam_siniri: ['ui_ux', 'deployment', 'hukuk', 'maliyet', 'izleme', 'veritabani_tasarimi', 'egitim', 'gereksinim'],
    durum: 'HAZIR', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'HY-04', kod_adi: 'HATAYÖN-DELTA', takim_kodu: 'HY', asama: A, uzmanlik_alani: 'Hata Yönetimi ve Kurtarma',
    gorev_tanimi: 'Kod içinde hataları yakalayıp sistemin çökmesini önleyen mekanizmaları tasarlar',
    beceriler: ['try_catch', 'graceful_degradation', 'circuit_breaker', 'fallback', 'hata_yakalama', 'hata_siniflandirma', 'retry_mekanizmasi', 'hata_loglama'],
    kapsam_siniri: ['ui_ux', 'deployment', 'hukuk', 'maliyet', 'izleme', 'veritabani_tasarimi', 'egitim', 'gereksinim'],
    durum: 'HAZIR', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'HY-05', kod_adi: 'HATAYÖN-ECHO', takim_kodu: 'HY', asama: A, uzmanlik_alani: 'Hata Yönetimi ve Kurtarma',
    gorev_tanimi: 'Kod içinde hataları yakalayıp sistemin çökmesini önleyen mekanizmaları tasarlar',
    beceriler: ['try_catch', 'graceful_degradation', 'circuit_breaker', 'fallback', 'hata_yakalama', 'hata_siniflandirma', 'retry_mekanizmasi', 'hata_loglama'],
    kapsam_siniri: ['ui_ux', 'deployment', 'hukuk', 'maliyet', 'izleme', 'veritabani_tasarimi', 'egitim', 'gereksinim'],
    durum: 'HAZIR', tamamlanan_gorev: 0, hata_sayisi: 0 },

  // ── BY: ÜÇÜNCÜ PARTİ BAĞIMLILIK YÖNETİMİ ──────────────────
  { id: 'BY-01', kod_adi: 'BAĞIMLILIK-ALFA', takim_kodu: 'BY', asama: A, uzmanlik_alani: 'Üçüncü Parti Bağımlılık Yönetimi',
    gorev_tanimi: 'Dış kütüphaneleri değerlendirir, güvenlik risklerini ve güncellik durumunu izler',
    beceriler: ['npm_ekosistemi', 'pip_ekosistemi', 'lisans_uyumu', 'guvenlik_acigi_tarama', 'dependency_audit', 'versiyon_kontrolu', 'guncellik_izleme', 'paket_degerlendirme'],
    kapsam_siniri: ['ui_ux', 'deployment', 'hukuk', 'maliyet', 'izleme', 'veritabani_tasarimi', 'egitim', 'gereksinim'],
    durum: 'HAZIR', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'BY-02', kod_adi: 'BAĞIMLILIK-BRAVO', takim_kodu: 'BY', asama: A, uzmanlik_alani: 'Üçüncü Parti Bağımlılık Yönetimi',
    gorev_tanimi: 'Dış kütüphaneleri değerlendirir, güvenlik risklerini ve güncellik durumunu izler',
    beceriler: ['npm_ekosistemi', 'pip_ekosistemi', 'lisans_uyumu', 'guvenlik_acigi_tarama', 'dependency_audit', 'versiyon_kontrolu', 'guncellik_izleme', 'paket_degerlendirme'],
    kapsam_siniri: ['ui_ux', 'deployment', 'hukuk', 'maliyet', 'izleme', 'veritabani_tasarimi', 'egitim', 'gereksinim'],
    durum: 'HAZIR', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'BY-03', kod_adi: 'BAĞIMLILIK-CHARLIE', takim_kodu: 'BY', asama: A, uzmanlik_alani: 'Üçüncü Parti Bağımlılık Yönetimi',
    gorev_tanimi: 'Dış kütüphaneleri değerlendirir, güvenlik risklerini ve güncellik durumunu izler',
    beceriler: ['npm_ekosistemi', 'pip_ekosistemi', 'lisans_uyumu', 'guvenlik_acigi_tarama', 'dependency_audit', 'versiyon_kontrolu', 'guncellik_izleme', 'paket_degerlendirme'],
    kapsam_siniri: ['ui_ux', 'deployment', 'hukuk', 'maliyet', 'izleme', 'veritabani_tasarimi', 'egitim', 'gereksinim'],
    durum: 'HAZIR', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'BY-04', kod_adi: 'BAĞIMLILIK-DELTA', takim_kodu: 'BY', asama: A, uzmanlik_alani: 'Üçüncü Parti Bağımlılık Yönetimi',
    gorev_tanimi: 'Dış kütüphaneleri değerlendirir, güvenlik risklerini ve güncellik durumunu izler',
    beceriler: ['npm_ekosistemi', 'pip_ekosistemi', 'lisans_uyumu', 'guvenlik_acigi_tarama', 'dependency_audit', 'versiyon_kontrolu', 'guncellik_izleme', 'paket_degerlendirme'],
    kapsam_siniri: ['ui_ux', 'deployment', 'hukuk', 'maliyet', 'izleme', 'veritabani_tasarimi', 'egitim', 'gereksinim'],
    durum: 'HAZIR', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'BY-05', kod_adi: 'BAĞIMLILIK-ECHO', takim_kodu: 'BY', asama: A, uzmanlik_alani: 'Üçüncü Parti Bağımlılık Yönetimi',
    gorev_tanimi: 'Dış kütüphaneleri değerlendirir, güvenlik risklerini ve güncellik durumunu izler',
    beceriler: ['npm_ekosistemi', 'pip_ekosistemi', 'lisans_uyumu', 'guvenlik_acigi_tarama', 'dependency_audit', 'versiyon_kontrolu', 'guncellik_izleme', 'paket_degerlendirme'],
    kapsam_siniri: ['ui_ux', 'deployment', 'hukuk', 'maliyet', 'izleme', 'veritabani_tasarimi', 'egitim', 'gereksinim'],
    durum: 'HAZIR', tamamlanan_gorev: 0, hata_sayisi: 0 },

  // ── ER: ERİŞİLEBİLİRLİK ────────────────────────────────────
  { id: 'ER-01', kod_adi: 'ERİŞİM-ALFA', takim_kodu: 'ER', asama: A, uzmanlik_alani: 'Erişilebilirlik',
    gorev_tanimi: 'Sistemi engelli kullanıcılar ve farklı cihazlar dahil herkes için kullanılabilir yapar',
    beceriler: ['wcag_standartlari', 'aria', 'klavye_navigasyon', 'ekran_okuyucu_uyumu', 'renk_kontrast', 'odak_yonetimi', 'alt_metin', 'erisilebilirlik_testi'],
    kapsam_siniri: ['deployment', 'veritabani', 'guvenlik', 'hukuk', 'maliyet', 'izleme', 'egitim', 'gereksinim'],
    durum: 'HAZIR', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'ER-02', kod_adi: 'ERİŞİM-BRAVO', takim_kodu: 'ER', asama: A, uzmanlik_alani: 'Erişilebilirlik',
    gorev_tanimi: 'Sistemi engelli kullanıcılar ve farklı cihazlar dahil herkes için kullanılabilir yapar',
    beceriler: ['wcag_standartlari', 'aria', 'klavye_navigasyon', 'ekran_okuyucu_uyumu', 'renk_kontrast', 'odak_yonetimi', 'alt_metin', 'erisilebilirlik_testi'],
    kapsam_siniri: ['deployment', 'veritabani', 'guvenlik', 'hukuk', 'maliyet', 'izleme', 'egitim', 'gereksinim'],
    durum: 'HAZIR', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'ER-03', kod_adi: 'ERİŞİM-CHARLIE', takim_kodu: 'ER', asama: A, uzmanlik_alani: 'Erişilebilirlik',
    gorev_tanimi: 'Sistemi engelli kullanıcılar ve farklı cihazlar dahil herkes için kullanılabilir yapar',
    beceriler: ['wcag_standartlari', 'aria', 'klavye_navigasyon', 'ekran_okuyucu_uyumu', 'renk_kontrast', 'odak_yonetimi', 'alt_metin', 'erisilebilirlik_testi'],
    kapsam_siniri: ['deployment', 'veritabani', 'guvenlik', 'hukuk', 'maliyet', 'izleme', 'egitim', 'gereksinim'],
    durum: 'HAZIR', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'ER-04', kod_adi: 'ERİŞİM-DELTA', takim_kodu: 'ER', asama: A, uzmanlik_alani: 'Erişilebilirlik',
    gorev_tanimi: 'Sistemi engelli kullanıcılar ve farklı cihazlar dahil herkes için kullanılabilir yapar',
    beceriler: ['wcag_standartlari', 'aria', 'klavye_navigasyon', 'ekran_okuyucu_uyumu', 'renk_kontrast', 'odak_yonetimi', 'alt_metin', 'erisilebilirlik_testi'],
    kapsam_siniri: ['deployment', 'veritabani', 'guvenlik', 'hukuk', 'maliyet', 'izleme', 'egitim', 'gereksinim'],
    durum: 'HAZIR', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'ER-05', kod_adi: 'ERİŞİM-ECHO', takim_kodu: 'ER', asama: A, uzmanlik_alani: 'Erişilebilirlik',
    gorev_tanimi: 'Sistemi engelli kullanıcılar ve farklı cihazlar dahil herkes için kullanılabilir yapar',
    beceriler: ['wcag_standartlari', 'aria', 'klavye_navigasyon', 'ekran_okuyucu_uyumu', 'renk_kontrast', 'odak_yonetimi', 'alt_metin', 'erisilebilirlik_testi'],
    kapsam_siniri: ['deployment', 'veritabani', 'guvenlik', 'hukuk', 'maliyet', 'izleme', 'egitim', 'gereksinim'],
    durum: 'HAZIR', tamamlanan_gorev: 0, hata_sayisi: 0 },

  // ── EN: ENTEGRASYON ─────────────────────────────────────────
  { id: 'EN-01', kod_adi: 'ENTEGRASYON-ALFA', takim_kodu: 'EN', asama: A, uzmanlik_alani: 'Entegrasyon',
    gorev_tanimi: 'Mevcut sistemlerle bağlantıyı kurar, veri alışverişini sağlar',
    beceriler: ['webhook', 'mesaj_kuyruklari', 'ucuncu_parti_api', 'veri_donusumu', 'sistem_baglantisi', 'protokol_uyumu', 'veri_alisverisi', 'entegrasyon_testi'],
    kapsam_siniri: ['ui_ux', 'hukuk', 'maliyet', 'izleme', 'dokumantasyon', 'egitim', 'gereksinim', 'risk'],
    durum: 'HAZIR', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'EN-02', kod_adi: 'ENTEGRASYON-BRAVO', takim_kodu: 'EN', asama: A, uzmanlik_alani: 'Entegrasyon',
    gorev_tanimi: 'Mevcut sistemlerle bağlantıyı kurar, veri alışverişini sağlar',
    beceriler: ['webhook', 'mesaj_kuyruklari', 'ucuncu_parti_api', 'veri_donusumu', 'sistem_baglantisi', 'protokol_uyumu', 'veri_alisverisi', 'entegrasyon_testi'],
    kapsam_siniri: ['ui_ux', 'hukuk', 'maliyet', 'izleme', 'dokumantasyon', 'egitim', 'gereksinim', 'risk'],
    durum: 'HAZIR', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'EN-03', kod_adi: 'ENTEGRASYON-CHARLIE', takim_kodu: 'EN', asama: A, uzmanlik_alani: 'Entegrasyon',
    gorev_tanimi: 'Mevcut sistemlerle bağlantıyı kurar, veri alışverişini sağlar',
    beceriler: ['webhook', 'mesaj_kuyruklari', 'ucuncu_parti_api', 'veri_donusumu', 'sistem_baglantisi', 'protokol_uyumu', 'veri_alisverisi', 'entegrasyon_testi'],
    kapsam_siniri: ['ui_ux', 'hukuk', 'maliyet', 'izleme', 'dokumantasyon', 'egitim', 'gereksinim', 'risk'],
    durum: 'HAZIR', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'EN-04', kod_adi: 'ENTEGRASYON-DELTA', takim_kodu: 'EN', asama: A, uzmanlik_alani: 'Entegrasyon',
    gorev_tanimi: 'Mevcut sistemlerle bağlantıyı kurar, veri alışverişini sağlar',
    beceriler: ['webhook', 'mesaj_kuyruklari', 'ucuncu_parti_api', 'veri_donusumu', 'sistem_baglantisi', 'protokol_uyumu', 'veri_alisverisi', 'entegrasyon_testi'],
    kapsam_siniri: ['ui_ux', 'hukuk', 'maliyet', 'izleme', 'dokumantasyon', 'egitim', 'gereksinim', 'risk'],
    durum: 'HAZIR', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'EN-05', kod_adi: 'ENTEGRASYON-ECHO', takim_kodu: 'EN', asama: A, uzmanlik_alani: 'Entegrasyon',
    gorev_tanimi: 'Mevcut sistemlerle bağlantıyı kurar, veri alışverişini sağlar',
    beceriler: ['webhook', 'mesaj_kuyruklari', 'ucuncu_parti_api', 'veri_donusumu', 'sistem_baglantisi', 'protokol_uyumu', 'veri_alisverisi', 'entegrasyon_testi'],
    kapsam_siniri: ['ui_ux', 'hukuk', 'maliyet', 'izleme', 'dokumantasyon', 'egitim', 'gereksinim', 'risk'],
    durum: 'HAZIR', tamamlanan_gorev: 0, hata_sayisi: 0 },
];

module.exports = { INSA };
