// ============================================================
// AŞAMA 4: DOĞRULAMA — 4 Takım × 5 Ajan = 20 Birim
// ============================================================
const { ASAMALAR } = require('./types');
const A = ASAMALAR.DOGRULAMA;

const DOGRULAMA = [

  // ── TE: TEST STRATEJİSİ ─────────────────────────────────────
  { id: 'TE-01', kod_adi: 'TEST-ALFA', takim_kodu: 'TE', asama: A, uzmanlik_alani: 'Test Stratejisi',
    gorev_tanimi: 'Neyin nasıl test edileceğini planlar, kabul kriterlerini belirler',
    beceriler: ['unit_test', 'integration_test', 'e2e_test', 'test_otomasyonu', 'tdd', 'bdd', 'kabul_kriterleri', 'test_planlama'],
    kapsam_siniri: ['deployment', 'ui_ux', 'hukuk', 'maliyet', 'izleme', 'veritabani_tasarimi', 'egitim', 'gereksinim'],
    durum: 'HAZIR', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'TE-02', kod_adi: 'TEST-BRAVO', takim_kodu: 'TE', asama: A, uzmanlik_alani: 'Test Stratejisi',
    gorev_tanimi: 'Neyin nasıl test edileceğini planlar, kabul kriterlerini belirler',
    beceriler: ['unit_test', 'integration_test', 'e2e_test', 'test_otomasyonu', 'tdd', 'bdd', 'kabul_kriterleri', 'test_planlama'],
    kapsam_siniri: ['deployment', 'ui_ux', 'hukuk', 'maliyet', 'izleme', 'veritabani_tasarimi', 'egitim', 'gereksinim'],
    durum: 'HAZIR', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'TE-03', kod_adi: 'TEST-CHARLIE', takim_kodu: 'TE', asama: A, uzmanlik_alani: 'Test Stratejisi',
    gorev_tanimi: 'Neyin nasıl test edileceğini planlar, kabul kriterlerini belirler',
    beceriler: ['unit_test', 'integration_test', 'e2e_test', 'test_otomasyonu', 'tdd', 'bdd', 'kabul_kriterleri', 'test_planlama'],
    kapsam_siniri: ['deployment', 'ui_ux', 'hukuk', 'maliyet', 'izleme', 'veritabani_tasarimi', 'egitim', 'gereksinim'],
    durum: 'HAZIR', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'TE-04', kod_adi: 'TEST-DELTA', takim_kodu: 'TE', asama: A, uzmanlik_alani: 'Test Stratejisi',
    gorev_tanimi: 'Neyin nasıl test edileceğini planlar, kabul kriterlerini belirler',
    beceriler: ['unit_test', 'integration_test', 'e2e_test', 'test_otomasyonu', 'tdd', 'bdd', 'kabul_kriterleri', 'test_planlama'],
    kapsam_siniri: ['deployment', 'ui_ux', 'hukuk', 'maliyet', 'izleme', 'veritabani_tasarimi', 'egitim', 'gereksinim'],
    durum: 'HAZIR', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'TE-05', kod_adi: 'TEST-ECHO', takim_kodu: 'TE', asama: A, uzmanlik_alani: 'Test Stratejisi',
    gorev_tanimi: 'Neyin nasıl test edileceğini planlar, kabul kriterlerini belirler',
    beceriler: ['unit_test', 'integration_test', 'e2e_test', 'test_otomasyonu', 'tdd', 'bdd', 'kabul_kriterleri', 'test_planlama'],
    kapsam_siniri: ['deployment', 'ui_ux', 'hukuk', 'maliyet', 'izleme', 'veritabani_tasarimi', 'egitim', 'gereksinim'],
    durum: 'HAZIR', tamamlanan_gorev: 0, hata_sayisi: 0 },

  // ── PO: PERFORMANS VE ÖLÇEKLENDİRME ────────────────────────
  { id: 'PO-01', kod_adi: 'PERFORMANS-ALFA', takim_kodu: 'PO', asama: A, uzmanlik_alani: 'Performans ve Ölçeklendirme',
    gorev_tanimi: 'Sistemin hıza ve yüke dayanıklılığını ölçer ve optimize eder',
    beceriler: ['load_testing', 'stress_testing', 'profiling', 'caching_stratejisi', 'sorgu_optimizasyonu', 'benchmark', 'bottleneck_analizi', 'olceklendirme'],
    kapsam_siniri: ['ui_ux', 'hukuk', 'maliyet', 'dokumantasyon', 'egitim', 'gereksinim', 'risk', 'mimari_tasarim'],
    durum: 'HAZIR', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'PO-02', kod_adi: 'PERFORMANS-BRAVO', takim_kodu: 'PO', asama: A, uzmanlik_alani: 'Performans ve Ölçeklendirme',
    gorev_tanimi: 'Sistemin hıza ve yüke dayanıklılığını ölçer ve optimize eder',
    beceriler: ['load_testing', 'stress_testing', 'profiling', 'caching_stratejisi', 'sorgu_optimizasyonu', 'benchmark', 'bottleneck_analizi', 'olceklendirme'],
    kapsam_siniri: ['ui_ux', 'hukuk', 'maliyet', 'dokumantasyon', 'egitim', 'gereksinim', 'risk', 'mimari_tasarim'],
    durum: 'HAZIR', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'PO-03', kod_adi: 'PERFORMANS-CHARLIE', takim_kodu: 'PO', asama: A, uzmanlik_alani: 'Performans ve Ölçeklendirme',
    gorev_tanimi: 'Sistemin hıza ve yüke dayanıklılığını ölçer ve optimize eder',
    beceriler: ['load_testing', 'stress_testing', 'profiling', 'caching_stratejisi', 'sorgu_optimizasyonu', 'benchmark', 'bottleneck_analizi', 'olceklendirme'],
    kapsam_siniri: ['ui_ux', 'hukuk', 'maliyet', 'dokumantasyon', 'egitim', 'gereksinim', 'risk', 'mimari_tasarim'],
    durum: 'HAZIR', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'PO-04', kod_adi: 'PERFORMANS-DELTA', takim_kodu: 'PO', asama: A, uzmanlik_alani: 'Performans ve Ölçeklendirme',
    gorev_tanimi: 'Sistemin hıza ve yüke dayanıklılığını ölçer ve optimize eder',
    beceriler: ['load_testing', 'stress_testing', 'profiling', 'caching_stratejisi', 'sorgu_optimizasyonu', 'benchmark', 'bottleneck_analizi', 'olceklendirme'],
    kapsam_siniri: ['ui_ux', 'hukuk', 'maliyet', 'dokumantasyon', 'egitim', 'gereksinim', 'risk', 'mimari_tasarim'],
    durum: 'HAZIR', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'PO-05', kod_adi: 'PERFORMANS-ECHO', takim_kodu: 'PO', asama: A, uzmanlik_alani: 'Performans ve Ölçeklendirme',
    gorev_tanimi: 'Sistemin hıza ve yüke dayanıklılığını ölçer ve optimize eder',
    beceriler: ['load_testing', 'stress_testing', 'profiling', 'caching_stratejisi', 'sorgu_optimizasyonu', 'benchmark', 'bottleneck_analizi', 'olceklendirme'],
    kapsam_siniri: ['ui_ux', 'hukuk', 'maliyet', 'dokumantasyon', 'egitim', 'gereksinim', 'risk', 'mimari_tasarim'],
    durum: 'HAZIR', tamamlanan_gorev: 0, hata_sayisi: 0 },

  // ── ST: GÜVENLİK TESTİ (SIZMA TESTİ) ───────────────────────
  { id: 'ST-01', kod_adi: 'SIZMA-ALFA', takim_kodu: 'ST', asama: A, uzmanlik_alani: 'Güvenlik Testi (Sızma Testi)',
    gorev_tanimi: 'Sisteme saldırarak açıkları bulur — tasarlayanın göremediğini görür',
    beceriler: ['penetrasyon_testi', 'owasp_top10', 'zaafiyet_tarama', 'red_team', 'saldiri_simulasyonu', 'acik_tespiti', 'exploit_analizi', 'guvenlik_raporu'],
    kapsam_siniri: ['ui_ux', 'hukuk', 'maliyet', 'dokumantasyon', 'egitim', 'gereksinim', 'mimari_tasarim', 'veri_modelleme'],
    durum: 'HAZIR', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'ST-02', kod_adi: 'SIZMA-BRAVO', takim_kodu: 'ST', asama: A, uzmanlik_alani: 'Güvenlik Testi (Sızma Testi)',
    gorev_tanimi: 'Sisteme saldırarak açıkları bulur — tasarlayanın göremediğini görür',
    beceriler: ['penetrasyon_testi', 'owasp_top10', 'zaafiyet_tarama', 'red_team', 'saldiri_simulasyonu', 'acik_tespiti', 'exploit_analizi', 'guvenlik_raporu'],
    kapsam_siniri: ['ui_ux', 'hukuk', 'maliyet', 'dokumantasyon', 'egitim', 'gereksinim', 'mimari_tasarim', 'veri_modelleme'],
    durum: 'HAZIR', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'ST-03', kod_adi: 'SIZMA-CHARLIE', takim_kodu: 'ST', asama: A, uzmanlik_alani: 'Güvenlik Testi (Sızma Testi)',
    gorev_tanimi: 'Sisteme saldırarak açıkları bulur — tasarlayanın göremediğini görür',
    beceriler: ['penetrasyon_testi', 'owasp_top10', 'zaafiyet_tarama', 'red_team', 'saldiri_simulasyonu', 'acik_tespiti', 'exploit_analizi', 'guvenlik_raporu'],
    kapsam_siniri: ['ui_ux', 'hukuk', 'maliyet', 'dokumantasyon', 'egitim', 'gereksinim', 'mimari_tasarim', 'veri_modelleme'],
    durum: 'HAZIR', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'ST-04', kod_adi: 'SIZMA-DELTA', takim_kodu: 'ST', asama: A, uzmanlik_alani: 'Güvenlik Testi (Sızma Testi)',
    gorev_tanimi: 'Sisteme saldırarak açıkları bulur — tasarlayanın göremediğini görür',
    beceriler: ['penetrasyon_testi', 'owasp_top10', 'zaafiyet_tarama', 'red_team', 'saldiri_simulasyonu', 'acik_tespiti', 'exploit_analizi', 'guvenlik_raporu'],
    kapsam_siniri: ['ui_ux', 'hukuk', 'maliyet', 'dokumantasyon', 'egitim', 'gereksinim', 'mimari_tasarim', 'veri_modelleme'],
    durum: 'HAZIR', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'ST-05', kod_adi: 'SIZMA-ECHO', takim_kodu: 'ST', asama: A, uzmanlik_alani: 'Güvenlik Testi (Sızma Testi)',
    gorev_tanimi: 'Sisteme saldırarak açıkları bulur — tasarlayanın göremediğini görür',
    beceriler: ['penetrasyon_testi', 'owasp_top10', 'zaafiyet_tarama', 'red_team', 'saldiri_simulasyonu', 'acik_tespiti', 'exploit_analizi', 'guvenlik_raporu'],
    kapsam_siniri: ['ui_ux', 'hukuk', 'maliyet', 'dokumantasyon', 'egitim', 'gereksinim', 'mimari_tasarim', 'veri_modelleme'],
    durum: 'HAZIR', tamamlanan_gorev: 0, hata_sayisi: 0 },

  // ── VA: VERİ AKIŞI VE İŞLEME ───────────────────────────────
  { id: 'VA-01', kod_adi: 'VERİAKIŞ-ALFA', takim_kodu: 'VA', asama: A, uzmanlik_alani: 'Veri Akışı ve İşleme',
    gorev_tanimi: 'Verinin sistem içinde nasıl hareket ettiğini, nasıl dönüştüğünü doğrular',
    beceriler: ['etl_surecleri', 'veri_dogrulama', 'veri_donusum_kurallari', 'pipeline_tasarimi', 'veri_akis_kontrol', 'veri_butunlugu', 'format_donusumu', 'veri_izleme'],
    kapsam_siniri: ['ui_ux', 'hukuk', 'maliyet', 'dokumantasyon', 'egitim', 'gereksinim', 'guvenlik_tasarimi', 'deployment'],
    durum: 'HAZIR', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'VA-02', kod_adi: 'VERİAKIŞ-BRAVO', takim_kodu: 'VA', asama: A, uzmanlik_alani: 'Veri Akışı ve İşleme',
    gorev_tanimi: 'Verinin sistem içinde nasıl hareket ettiğini, nasıl dönüştüğünü doğrular',
    beceriler: ['etl_surecleri', 'veri_dogrulama', 'veri_donusum_kurallari', 'pipeline_tasarimi', 'veri_akis_kontrol', 'veri_butunlugu', 'format_donusumu', 'veri_izleme'],
    kapsam_siniri: ['ui_ux', 'hukuk', 'maliyet', 'dokumantasyon', 'egitim', 'gereksinim', 'guvenlik_tasarimi', 'deployment'],
    durum: 'HAZIR', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'VA-03', kod_adi: 'VERİAKIŞ-CHARLIE', takim_kodu: 'VA', asama: A, uzmanlik_alani: 'Veri Akışı ve İşleme',
    gorev_tanimi: 'Verinin sistem içinde nasıl hareket ettiğini, nasıl dönüştüğünü doğrular',
    beceriler: ['etl_surecleri', 'veri_dogrulama', 'veri_donusum_kurallari', 'pipeline_tasarimi', 'veri_akis_kontrol', 'veri_butunlugu', 'format_donusumu', 'veri_izleme'],
    kapsam_siniri: ['ui_ux', 'hukuk', 'maliyet', 'dokumantasyon', 'egitim', 'gereksinim', 'guvenlik_tasarimi', 'deployment'],
    durum: 'HAZIR', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'VA-04', kod_adi: 'VERİAKIŞ-DELTA', takim_kodu: 'VA', asama: A, uzmanlik_alani: 'Veri Akışı ve İşleme',
    gorev_tanimi: 'Verinin sistem içinde nasıl hareket ettiğini, nasıl dönüştüğünü doğrular',
    beceriler: ['etl_surecleri', 'veri_dogrulama', 'veri_donusum_kurallari', 'pipeline_tasarimi', 'veri_akis_kontrol', 'veri_butunlugu', 'format_donusumu', 'veri_izleme'],
    kapsam_siniri: ['ui_ux', 'hukuk', 'maliyet', 'dokumantasyon', 'egitim', 'gereksinim', 'guvenlik_tasarimi', 'deployment'],
    durum: 'HAZIR', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'VA-05', kod_adi: 'VERİAKIŞ-ECHO', takim_kodu: 'VA', asama: A, uzmanlik_alani: 'Veri Akışı ve İşleme',
    gorev_tanimi: 'Verinin sistem içinde nasıl hareket ettiğini, nasıl dönüştüğünü doğrular',
    beceriler: ['etl_surecleri', 'veri_dogrulama', 'veri_donusum_kurallari', 'pipeline_tasarimi', 'veri_akis_kontrol', 'veri_butunlugu', 'format_donusumu', 'veri_izleme'],
    kapsam_siniri: ['ui_ux', 'hukuk', 'maliyet', 'dokumantasyon', 'egitim', 'gereksinim', 'guvenlik_tasarimi', 'deployment'],
    durum: 'HAZIR', tamamlanan_gorev: 0, hata_sayisi: 0 },
];

module.exports = { DOGRULAMA };
