// ============================================================
// AŞAMA 5: YAYINLAMA — 3 Takım × 5 Ajan = 15 Birim
// ============================================================
const { ASAMALAR } = require('./types');
const A = ASAMALAR.YAYINLAMA;

const YAYINLAMA = [

  // ── DO: DEVOPS / CI-CD ──────────────────────────────────────
  { id: 'DO-01', kod_adi: 'DEVOPS-ALFA', takim_kodu: 'DO', asama: A, uzmanlik_alani: 'DevOps / CI-CD',
    gorev_tanimi: 'Kodu geliştirmeden üretime taşıyan otomatik boru hattını kurar',
    beceriler: ['github_actions', 'docker', 'kubernetes', 'ortam_yonetimi', 'secret_management', 'ci_cd_pipeline', 'build_otomasyon', 'deploy_stratejisi'],
    kapsam_siniri: ['ui_ux', 'hukuk', 'maliyet', 'dokumantasyon', 'egitim', 'gereksinim', 'risk', 'veri_modelleme'],
    durum: 'aktif', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'DO-02', kod_adi: 'DEVOPS-BRAVO', takim_kodu: 'DO', asama: A, uzmanlik_alani: 'DevOps / CI-CD',
    gorev_tanimi: 'Kodu geliştirmeden üretime taşıyan otomatik boru hattını kurar',
    beceriler: ['github_actions', 'docker', 'kubernetes', 'ortam_yonetimi', 'secret_management', 'ci_cd_pipeline', 'build_otomasyon', 'deploy_stratejisi'],
    kapsam_siniri: ['ui_ux', 'hukuk', 'maliyet', 'dokumantasyon', 'egitim', 'gereksinim', 'risk', 'veri_modelleme'],
    durum: 'aktif', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'DO-03', kod_adi: 'DEVOPS-CHARLIE', takim_kodu: 'DO', asama: A, uzmanlik_alani: 'DevOps / CI-CD',
    gorev_tanimi: 'Kodu geliştirmeden üretime taşıyan otomatik boru hattını kurar',
    beceriler: ['github_actions', 'docker', 'kubernetes', 'ortam_yonetimi', 'secret_management', 'ci_cd_pipeline', 'build_otomasyon', 'deploy_stratejisi'],
    kapsam_siniri: ['ui_ux', 'hukuk', 'maliyet', 'dokumantasyon', 'egitim', 'gereksinim', 'risk', 'veri_modelleme'],
    durum: 'aktif', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'DO-04', kod_adi: 'DEVOPS-DELTA', takim_kodu: 'DO', asama: A, uzmanlik_alani: 'DevOps / CI-CD',
    gorev_tanimi: 'Kodu geliştirmeden üretime taşıyan otomatik boru hattını kurar',
    beceriler: ['github_actions', 'docker', 'kubernetes', 'ortam_yonetimi', 'secret_management', 'ci_cd_pipeline', 'build_otomasyon', 'deploy_stratejisi'],
    kapsam_siniri: ['ui_ux', 'hukuk', 'maliyet', 'dokumantasyon', 'egitim', 'gereksinim', 'risk', 'veri_modelleme'],
    durum: 'aktif', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'DO-05', kod_adi: 'DEVOPS-ECHO', takim_kodu: 'DO', asama: A, uzmanlik_alani: 'DevOps / CI-CD',
    gorev_tanimi: 'Kodu geliştirmeden üretime taşıyan otomatik boru hattını kurar',
    beceriler: ['github_actions', 'docker', 'kubernetes', 'ortam_yonetimi', 'secret_management', 'ci_cd_pipeline', 'build_otomasyon', 'deploy_stratejisi'],
    kapsam_siniri: ['ui_ux', 'hukuk', 'maliyet', 'dokumantasyon', 'egitim', 'gereksinim', 'risk', 'veri_modelleme'],
    durum: 'aktif', tamamlanan_gorev: 0, hata_sayisi: 0 },

  // ── GM: GÖÇ / MİGRASYON ────────────────────────────────────
  { id: 'GM-01', kod_adi: 'MİGRASYON-ALFA', takim_kodu: 'GM', asama: A, uzmanlik_alani: 'Göç / Migrasyon',
    gorev_tanimi: 'Eski sistemden yeniye geçişi planlar — veri taşıma, uyumluluk, kesintisiz geçiş',
    beceriler: ['veri_migrasyon', 'schema_migration', 'geriye_uyumluluk', 'blue_green_deployment', 'veri_tasima', 'kesintisiz_gecis', 'rollback_plani', 'uyumluluk_testi'],
    kapsam_siniri: ['ui_ux', 'hukuk', 'maliyet', 'dokumantasyon', 'egitim', 'gereksinim', 'risk', 'guvenlik_testi'],
    durum: 'aktif', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'GM-02', kod_adi: 'MİGRASYON-BRAVO', takim_kodu: 'GM', asama: A, uzmanlik_alani: 'Göç / Migrasyon',
    gorev_tanimi: 'Eski sistemden yeniye geçişi planlar — veri taşıma, uyumluluk, kesintisiz geçiş',
    beceriler: ['veri_migrasyon', 'schema_migration', 'geriye_uyumluluk', 'blue_green_deployment', 'veri_tasima', 'kesintisiz_gecis', 'rollback_plani', 'uyumluluk_testi'],
    kapsam_siniri: ['ui_ux', 'hukuk', 'maliyet', 'dokumantasyon', 'egitim', 'gereksinim', 'risk', 'guvenlik_testi'],
    durum: 'aktif', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'GM-03', kod_adi: 'MİGRASYON-CHARLIE', takim_kodu: 'GM', asama: A, uzmanlik_alani: 'Göç / Migrasyon',
    gorev_tanimi: 'Eski sistemden yeniye geçişi planlar — veri taşıma, uyumluluk, kesintisiz geçiş',
    beceriler: ['veri_migrasyon', 'schema_migration', 'geriye_uyumluluk', 'blue_green_deployment', 'veri_tasima', 'kesintisiz_gecis', 'rollback_plani', 'uyumluluk_testi'],
    kapsam_siniri: ['ui_ux', 'hukuk', 'maliyet', 'dokumantasyon', 'egitim', 'gereksinim', 'risk', 'guvenlik_testi'],
    durum: 'aktif', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'GM-04', kod_adi: 'MİGRASYON-DELTA', takim_kodu: 'GM', asama: A, uzmanlik_alani: 'Göç / Migrasyon',
    gorev_tanimi: 'Eski sistemden yeniye geçişi planlar — veri taşıma, uyumluluk, kesintisiz geçiş',
    beceriler: ['veri_migrasyon', 'schema_migration', 'geriye_uyumluluk', 'blue_green_deployment', 'veri_tasima', 'kesintisiz_gecis', 'rollback_plani', 'uyumluluk_testi'],
    kapsam_siniri: ['ui_ux', 'hukuk', 'maliyet', 'dokumantasyon', 'egitim', 'gereksinim', 'risk', 'guvenlik_testi'],
    durum: 'aktif', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'GM-05', kod_adi: 'MİGRASYON-ECHO', takim_kodu: 'GM', asama: A, uzmanlik_alani: 'Göç / Migrasyon',
    gorev_tanimi: 'Eski sistemden yeniye geçişi planlar — veri taşıma, uyumluluk, kesintisiz geçiş',
    beceriler: ['veri_migrasyon', 'schema_migration', 'geriye_uyumluluk', 'blue_green_deployment', 'veri_tasima', 'kesintisiz_gecis', 'rollback_plani', 'uyumluluk_testi'],
    kapsam_siniri: ['ui_ux', 'hukuk', 'maliyet', 'dokumantasyon', 'egitim', 'gereksinim', 'risk', 'guvenlik_testi'],
    durum: 'aktif', tamamlanan_gorev: 0, hata_sayisi: 0 },

  // ── SY: SÜRÜM VE YAYIN YÖNETİMİ ───────────────────────────
  { id: 'SY-01', kod_adi: 'SÜRÜM-ALFA', takim_kodu: 'SY', asama: A, uzmanlik_alani: 'Sürüm ve Yayın Yönetimi',
    gorev_tanimi: 'Ne zaman, hangi sürümle yayınlanacak, geri alma stratejisi ne olacak karar verir',
    beceriler: ['semantic_versioning', 'changelog', 'release_planning', 'rollback_stratejisi', 'surum_etiketleme', 'yayin_takvimi', 'geri_alma', 'surum_notlari'],
    kapsam_siniri: ['ui_ux', 'hukuk', 'maliyet', 'dokumantasyon', 'egitim', 'gereksinim', 'risk', 'guvenlik_testi'],
    durum: 'aktif', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'SY-02', kod_adi: 'SÜRÜM-BRAVO', takim_kodu: 'SY', asama: A, uzmanlik_alani: 'Sürüm ve Yayın Yönetimi',
    gorev_tanimi: 'Ne zaman, hangi sürümle yayınlanacak, geri alma stratejisi ne olacak karar verir',
    beceriler: ['semantic_versioning', 'changelog', 'release_planning', 'rollback_stratejisi', 'surum_etiketleme', 'yayin_takvimi', 'geri_alma', 'surum_notlari'],
    kapsam_siniri: ['ui_ux', 'hukuk', 'maliyet', 'dokumantasyon', 'egitim', 'gereksinim', 'risk', 'guvenlik_testi'],
    durum: 'aktif', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'SY-03', kod_adi: 'SÜRÜM-CHARLIE', takim_kodu: 'SY', asama: A, uzmanlik_alani: 'Sürüm ve Yayın Yönetimi',
    gorev_tanimi: 'Ne zaman, hangi sürümle yayınlanacak, geri alma stratejisi ne olacak karar verir',
    beceriler: ['semantic_versioning', 'changelog', 'release_planning', 'rollback_stratejisi', 'surum_etiketleme', 'yayin_takvimi', 'geri_alma', 'surum_notlari'],
    kapsam_siniri: ['ui_ux', 'hukuk', 'maliyet', 'dokumantasyon', 'egitim', 'gereksinim', 'risk', 'guvenlik_testi'],
    durum: 'aktif', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'SY-04', kod_adi: 'SÜRÜM-DELTA', takim_kodu: 'SY', asama: A, uzmanlik_alani: 'Sürüm ve Yayın Yönetimi',
    gorev_tanimi: 'Ne zaman, hangi sürümle yayınlanacak, geri alma stratejisi ne olacak karar verir',
    beceriler: ['semantic_versioning', 'changelog', 'release_planning', 'rollback_stratejisi', 'surum_etiketleme', 'yayin_takvimi', 'geri_alma', 'surum_notlari'],
    kapsam_siniri: ['ui_ux', 'hukuk', 'maliyet', 'dokumantasyon', 'egitim', 'gereksinim', 'risk', 'guvenlik_testi'],
    durum: 'aktif', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'SY-05', kod_adi: 'SÜRÜM-ECHO', takim_kodu: 'SY', asama: A, uzmanlik_alani: 'Sürüm ve Yayın Yönetimi',
    gorev_tanimi: 'Ne zaman, hangi sürümle yayınlanacak, geri alma stratejisi ne olacak karar verir',
    beceriler: ['semantic_versioning', 'changelog', 'release_planning', 'rollback_stratejisi', 'surum_etiketleme', 'yayin_takvimi', 'geri_alma', 'surum_notlari'],
    kapsam_siniri: ['ui_ux', 'hukuk', 'maliyet', 'dokumantasyon', 'egitim', 'gereksinim', 'risk', 'guvenlik_testi'],
    durum: 'aktif', tamamlanan_gorev: 0, hata_sayisi: 0 },
];

module.exports = { YAYINLAMA };
