// ============================================================
// AŞAMA 6: YAŞATMA — 8 Takım × 5 Ajan = 40 Birim
// ============================================================
const { ASAMALAR } = require('./types');
const A = ASAMALAR.YASATMA;

const YASATMA = [

  // ── OP: OPERASYON (ÇALIŞTIRMA) ──────────────────────────────
  { id: 'OP-01', kod_adi: 'OPERASYON-ALFA', takim_kodu: 'OP', asama: A, uzmanlik_alani: 'Operasyon (Çalıştırma)',
    gorev_tanimi: 'Sistemi canlıda ayakta tutar, günlük işletme süreçlerini yönetir',
    beceriler: ['sistem_yonetimi', 'surec_izleme', 'kaynak_yonetimi', 'rutin_bakim', 'servis_yonetimi', 'isletme_sureci', 'kapasite_izleme', 'saglik_kontrolu'],
    kapsam_siniri: ['kod_yazma', 'tasarim', 'test', 'hukuk', 'maliyet', 'gereksinim', 'risk', 'ui_ux'],
    durum: 'aktif', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'OP-02', kod_adi: 'OPERASYON-BRAVO', takim_kodu: 'OP', asama: A, uzmanlik_alani: 'Operasyon (Çalıştırma)',
    gorev_tanimi: 'Sistemi canlıda ayakta tutar, günlük işletme süreçlerini yönetir',
    beceriler: ['sistem_yonetimi', 'surec_izleme', 'kaynak_yonetimi', 'rutin_bakim', 'servis_yonetimi', 'isletme_sureci', 'kapasite_izleme', 'saglik_kontrolu'],
    kapsam_siniri: ['kod_yazma', 'tasarim', 'test', 'hukuk', 'maliyet', 'gereksinim', 'risk', 'ui_ux'],
    durum: 'aktif', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'OP-03', kod_adi: 'OPERASYON-CHARLIE', takim_kodu: 'OP', asama: A, uzmanlik_alani: 'Operasyon (Çalıştırma)',
    gorev_tanimi: 'Sistemi canlıda ayakta tutar, günlük işletme süreçlerini yönetir',
    beceriler: ['sistem_yonetimi', 'surec_izleme', 'kaynak_yonetimi', 'rutin_bakim', 'servis_yonetimi', 'isletme_sureci', 'kapasite_izleme', 'saglik_kontrolu'],
    kapsam_siniri: ['kod_yazma', 'tasarim', 'test', 'hukuk', 'maliyet', 'gereksinim', 'risk', 'ui_ux'],
    durum: 'aktif', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'OP-04', kod_adi: 'OPERASYON-DELTA', takim_kodu: 'OP', asama: A, uzmanlik_alani: 'Operasyon (Çalıştırma)',
    gorev_tanimi: 'Sistemi canlıda ayakta tutar, günlük işletme süreçlerini yönetir',
    beceriler: ['sistem_yonetimi', 'surec_izleme', 'kaynak_yonetimi', 'rutin_bakim', 'servis_yonetimi', 'isletme_sureci', 'kapasite_izleme', 'saglik_kontrolu'],
    kapsam_siniri: ['kod_yazma', 'tasarim', 'test', 'hukuk', 'maliyet', 'gereksinim', 'risk', 'ui_ux'],
    durum: 'aktif', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'OP-05', kod_adi: 'OPERASYON-ECHO', takim_kodu: 'OP', asama: A, uzmanlik_alani: 'Operasyon (Çalıştırma)',
    gorev_tanimi: 'Sistemi canlıda ayakta tutar, günlük işletme süreçlerini yönetir',
    beceriler: ['sistem_yonetimi', 'surec_izleme', 'kaynak_yonetimi', 'rutin_bakim', 'servis_yonetimi', 'isletme_sureci', 'kapasite_izleme', 'saglik_kontrolu'],
    kapsam_siniri: ['kod_yazma', 'tasarim', 'test', 'hukuk', 'maliyet', 'gereksinim', 'risk', 'ui_ux'],
    durum: 'aktif', tamamlanan_gorev: 0, hata_sayisi: 0 },

  // ── CI: CANLI İZLEME VE ALARM ───────────────────────────────
  { id: 'CI-01', kod_adi: 'İZLEME-ALFA', takim_kodu: 'CI', asama: A, uzmanlik_alani: 'Canlı İzleme ve Alarm',
    gorev_tanimi: 'Sistem sağlığını anlık takip eder, anormal durumda alarm verir',
    beceriler: ['prometheus', 'grafana', 'log_analizi', 'uptime_monitoring', 'alert_kurallari', 'anomali_tespiti', 'metrik_toplama', 'dashboard_izleme'],
    kapsam_siniri: ['kod_yazma', 'tasarim', 'test', 'hukuk', 'maliyet', 'gereksinim', 'risk', 'ui_ux'],
    durum: 'aktif', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'CI-02', kod_adi: 'İZLEME-BRAVO', takim_kodu: 'CI', asama: A, uzmanlik_alani: 'Canlı İzleme ve Alarm',
    gorev_tanimi: 'Sistem sağlığını anlık takip eder, anormal durumda alarm verir',
    beceriler: ['prometheus', 'grafana', 'log_analizi', 'uptime_monitoring', 'alert_kurallari', 'anomali_tespiti', 'metrik_toplama', 'dashboard_izleme'],
    kapsam_siniri: ['kod_yazma', 'tasarim', 'test', 'hukuk', 'maliyet', 'gereksinim', 'risk', 'ui_ux'],
    durum: 'aktif', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'CI-03', kod_adi: 'İZLEME-CHARLIE', takim_kodu: 'CI', asama: A, uzmanlik_alani: 'Canlı İzleme ve Alarm',
    gorev_tanimi: 'Sistem sağlığını anlık takip eder, anormal durumda alarm verir',
    beceriler: ['prometheus', 'grafana', 'log_analizi', 'uptime_monitoring', 'alert_kurallari', 'anomali_tespiti', 'metrik_toplama', 'dashboard_izleme'],
    kapsam_siniri: ['kod_yazma', 'tasarim', 'test', 'hukuk', 'maliyet', 'gereksinim', 'risk', 'ui_ux'],
    durum: 'aktif', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'CI-04', kod_adi: 'İZLEME-DELTA', takim_kodu: 'CI', asama: A, uzmanlik_alani: 'Canlı İzleme ve Alarm',
    gorev_tanimi: 'Sistem sağlığını anlık takip eder, anormal durumda alarm verir',
    beceriler: ['prometheus', 'grafana', 'log_analizi', 'uptime_monitoring', 'alert_kurallari', 'anomali_tespiti', 'metrik_toplama', 'dashboard_izleme'],
    kapsam_siniri: ['kod_yazma', 'tasarim', 'test', 'hukuk', 'maliyet', 'gereksinim', 'risk', 'ui_ux'],
    durum: 'aktif', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'CI-05', kod_adi: 'İZLEME-ECHO', takim_kodu: 'CI', asama: A, uzmanlik_alani: 'Canlı İzleme ve Alarm',
    gorev_tanimi: 'Sistem sağlığını anlık takip eder, anormal durumda alarm verir',
    beceriler: ['prometheus', 'grafana', 'log_analizi', 'uptime_monitoring', 'alert_kurallari', 'anomali_tespiti', 'metrik_toplama', 'dashboard_izleme'],
    kapsam_siniri: ['kod_yazma', 'tasarim', 'test', 'hukuk', 'maliyet', 'gereksinim', 'risk', 'ui_ux'],
    durum: 'aktif', tamamlanan_gorev: 0, hata_sayisi: 0 },

  // ── YF: YEDEKLEME VE FELAKET KURTARMA ───────────────────────
  { id: 'YF-01', kod_adi: 'YEDEK-ALFA', takim_kodu: 'YF', asama: A, uzmanlik_alani: 'Yedekleme ve Felaket Kurtarma',
    gorev_tanimi: 'Veri kaybını önler, felaket durumunda sistemi ayağa kaldırır',
    beceriler: ['backup_stratejileri', 'rto_rpo_hesaplama', 'disaster_recovery', 'replikasyon', 'snapshot', 'veri_kurtarma', 'felaket_plani', 'yedek_dogrulama'],
    kapsam_siniri: ['kod_yazma', 'tasarim', 'test', 'hukuk', 'maliyet', 'gereksinim', 'risk', 'ui_ux'],
    durum: 'aktif', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'YF-02', kod_adi: 'YEDEK-BRAVO', takim_kodu: 'YF', asama: A, uzmanlik_alani: 'Yedekleme ve Felaket Kurtarma',
    gorev_tanimi: 'Veri kaybını önler, felaket durumunda sistemi ayağa kaldırır',
    beceriler: ['backup_stratejileri', 'rto_rpo_hesaplama', 'disaster_recovery', 'replikasyon', 'snapshot', 'veri_kurtarma', 'felaket_plani', 'yedek_dogrulama'],
    kapsam_siniri: ['kod_yazma', 'tasarim', 'test', 'hukuk', 'maliyet', 'gereksinim', 'risk', 'ui_ux'],
    durum: 'aktif', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'YF-03', kod_adi: 'YEDEK-CHARLIE', takim_kodu: 'YF', asama: A, uzmanlik_alani: 'Yedekleme ve Felaket Kurtarma',
    gorev_tanimi: 'Veri kaybını önler, felaket durumunda sistemi ayağa kaldırır',
    beceriler: ['backup_stratejileri', 'rto_rpo_hesaplama', 'disaster_recovery', 'replikasyon', 'snapshot', 'veri_kurtarma', 'felaket_plani', 'yedek_dogrulama'],
    kapsam_siniri: ['kod_yazma', 'tasarim', 'test', 'hukuk', 'maliyet', 'gereksinim', 'risk', 'ui_ux'],
    durum: 'aktif', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'YF-04', kod_adi: 'YEDEK-DELTA', takim_kodu: 'YF', asama: A, uzmanlik_alani: 'Yedekleme ve Felaket Kurtarma',
    gorev_tanimi: 'Veri kaybını önler, felaket durumunda sistemi ayağa kaldırır',
    beceriler: ['backup_stratejileri', 'rto_rpo_hesaplama', 'disaster_recovery', 'replikasyon', 'snapshot', 'veri_kurtarma', 'felaket_plani', 'yedek_dogrulama'],
    kapsam_siniri: ['kod_yazma', 'tasarim', 'test', 'hukuk', 'maliyet', 'gereksinim', 'risk', 'ui_ux'],
    durum: 'aktif', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'YF-05', kod_adi: 'YEDEK-ECHO', takim_kodu: 'YF', asama: A, uzmanlik_alani: 'Yedekleme ve Felaket Kurtarma',
    gorev_tanimi: 'Veri kaybını önler, felaket durumunda sistemi ayağa kaldırır',
    beceriler: ['backup_stratejileri', 'rto_rpo_hesaplama', 'disaster_recovery', 'replikasyon', 'snapshot', 'veri_kurtarma', 'felaket_plani', 'yedek_dogrulama'],
    kapsam_siniri: ['kod_yazma', 'tasarim', 'test', 'hukuk', 'maliyet', 'gereksinim', 'risk', 'ui_ux'],
    durum: 'aktif', tamamlanan_gorev: 0, hata_sayisi: 0 },

  // ── SD: SİSTEM DENETİMİ VE KONTROL ─────────────────────────
  { id: 'SD-01', kod_adi: 'DENETİM-ALFA', takim_kodu: 'SD', asama: A, uzmanlik_alani: 'Sistem Denetimi ve Kontrol',
    gorev_tanimi: 'Sistemin standartlara ve kurallara uygunluğunu denetler',
    beceriler: ['audit_metodolojisi', 'compliance_kontrol', 'kalite_guvence', 'standart_denetimi', 'kural_uyumu', 'denetim_raporu', 'uyumsuzluk_tespiti', 'duzeltici_eylem'],
    kapsam_siniri: ['kod_yazma', 'tasarim', 'deployment', 'hukuk', 'maliyet', 'gereksinim', 'risk', 'ui_ux'],
    durum: 'aktif', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'SD-02', kod_adi: 'DENETİM-BRAVO', takim_kodu: 'SD', asama: A, uzmanlik_alani: 'Sistem Denetimi ve Kontrol',
    gorev_tanimi: 'Sistemin standartlara ve kurallara uygunluğunu denetler',
    beceriler: ['audit_metodolojisi', 'compliance_kontrol', 'kalite_guvence', 'standart_denetimi', 'kural_uyumu', 'denetim_raporu', 'uyumsuzluk_tespiti', 'duzeltici_eylem'],
    kapsam_siniri: ['kod_yazma', 'tasarim', 'deployment', 'hukuk', 'maliyet', 'gereksinim', 'risk', 'ui_ux'],
    durum: 'aktif', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'SD-03', kod_adi: 'DENETİM-CHARLIE', takim_kodu: 'SD', asama: A, uzmanlik_alani: 'Sistem Denetimi ve Kontrol',
    gorev_tanimi: 'Sistemin standartlara ve kurallara uygunluğunu denetler',
    beceriler: ['audit_metodolojisi', 'compliance_kontrol', 'kalite_guvence', 'standart_denetimi', 'kural_uyumu', 'denetim_raporu', 'uyumsuzluk_tespiti', 'duzeltici_eylem'],
    kapsam_siniri: ['kod_yazma', 'tasarim', 'deployment', 'hukuk', 'maliyet', 'gereksinim', 'risk', 'ui_ux'],
    durum: 'aktif', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'SD-04', kod_adi: 'DENETİM-DELTA', takim_kodu: 'SD', asama: A, uzmanlik_alani: 'Sistem Denetimi ve Kontrol',
    gorev_tanimi: 'Sistemin standartlara ve kurallara uygunluğunu denetler',
    beceriler: ['audit_metodolojisi', 'compliance_kontrol', 'kalite_guvence', 'standart_denetimi', 'kural_uyumu', 'denetim_raporu', 'uyumsuzluk_tespiti', 'duzeltici_eylem'],
    kapsam_siniri: ['kod_yazma', 'tasarim', 'deployment', 'hukuk', 'maliyet', 'gereksinim', 'risk', 'ui_ux'],
    durum: 'aktif', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'SD-05', kod_adi: 'DENETİM-ECHO', takim_kodu: 'SD', asama: A, uzmanlik_alani: 'Sistem Denetimi ve Kontrol',
    gorev_tanimi: 'Sistemin standartlara ve kurallara uygunluğunu denetler',
    beceriler: ['audit_metodolojisi', 'compliance_kontrol', 'kalite_guvence', 'standart_denetimi', 'kural_uyumu', 'denetim_raporu', 'uyumsuzluk_tespiti', 'duzeltici_eylem'],
    kapsam_siniri: ['kod_yazma', 'tasarim', 'deployment', 'hukuk', 'maliyet', 'gereksinim', 'risk', 'ui_ux'],
    durum: 'aktif', tamamlanan_gorev: 0, hata_sayisi: 0 },

  // ── HT: HATA TESPİTİ VE TEŞHİS ────────────────────────────
  { id: 'HT-01', kod_adi: 'TESPİT-ALFA', takim_kodu: 'HT', asama: A, uzmanlik_alani: 'Hata Tespiti ve Teşhis',
    gorev_tanimi: 'Canlı sistemde sorunları bulur, kök nedeni teşhis eder',
    beceriler: ['debugging', 'log_analizi', 'root_cause_analysis', 'hata_yeniden_uretme', 'stack_trace', 'kok_neden', 'hata_izleme', 'reproduksiyon'],
    kapsam_siniri: ['kod_yazma', 'tasarim', 'deployment', 'hukuk', 'maliyet', 'gereksinim', 'risk', 'ui_ux'],
    durum: 'aktif', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'HT-02', kod_adi: 'TESPİT-BRAVO', takim_kodu: 'HT', asama: A, uzmanlik_alani: 'Hata Tespiti ve Teşhis',
    gorev_tanimi: 'Canlı sistemde sorunları bulur, kök nedeni teşhis eder',
    beceriler: ['debugging', 'log_analizi', 'root_cause_analysis', 'hata_yeniden_uretme', 'stack_trace', 'kok_neden', 'hata_izleme', 'reproduksiyon'],
    kapsam_siniri: ['kod_yazma', 'tasarim', 'deployment', 'hukuk', 'maliyet', 'gereksinim', 'risk', 'ui_ux'],
    durum: 'aktif', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'HT-03', kod_adi: 'TESPİT-CHARLIE', takim_kodu: 'HT', asama: A, uzmanlik_alani: 'Hata Tespiti ve Teşhis',
    gorev_tanimi: 'Canlı sistemde sorunları bulur, kök nedeni teşhis eder',
    beceriler: ['debugging', 'log_analizi', 'root_cause_analysis', 'hata_yeniden_uretme', 'stack_trace', 'kok_neden', 'hata_izleme', 'reproduksiyon'],
    kapsam_siniri: ['kod_yazma', 'tasarim', 'deployment', 'hukuk', 'maliyet', 'gereksinim', 'risk', 'ui_ux'],
    durum: 'aktif', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'HT-04', kod_adi: 'TESPİT-DELTA', takim_kodu: 'HT', asama: A, uzmanlik_alani: 'Hata Tespiti ve Teşhis',
    gorev_tanimi: 'Canlı sistemde sorunları bulur, kök nedeni teşhis eder',
    beceriler: ['debugging', 'log_analizi', 'root_cause_analysis', 'hata_yeniden_uretme', 'stack_trace', 'kok_neden', 'hata_izleme', 'reproduksiyon'],
    kapsam_siniri: ['kod_yazma', 'tasarim', 'deployment', 'hukuk', 'maliyet', 'gereksinim', 'risk', 'ui_ux'],
    durum: 'aktif', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'HT-05', kod_adi: 'TESPİT-ECHO', takim_kodu: 'HT', asama: A, uzmanlik_alani: 'Hata Tespiti ve Teşhis',
    gorev_tanimi: 'Canlı sistemde sorunları bulur, kök nedeni teşhis eder',
    beceriler: ['debugging', 'log_analizi', 'root_cause_analysis', 'hata_yeniden_uretme', 'stack_trace', 'kok_neden', 'hata_izleme', 'reproduksiyon'],
    kapsam_siniri: ['kod_yazma', 'tasarim', 'deployment', 'hukuk', 'maliyet', 'gereksinim', 'risk', 'ui_ux'],
    durum: 'aktif', tamamlanan_gorev: 0, hata_sayisi: 0 },

  // ── HO: HATA ONARIMI VE DÜZELTME ───────────────────────────
  { id: 'HO-01', kod_adi: 'ONARIM-ALFA', takim_kodu: 'HO', asama: A, uzmanlik_alani: 'Hata Onarımı ve Düzeltme',
    gorev_tanimi: 'Tespit edilen hataları düzeltir, yama yapar',
    beceriler: ['hotfix', 'patch_yonetimi', 'regresyon_onleme', 'kod_duzeltme', 'yama_uygulama', 'hata_giderme', 'acil_mudahale', 'duzeltme_dogrulama'],
    kapsam_siniri: ['tasarim', 'deployment', 'hukuk', 'maliyet', 'gereksinim', 'risk', 'ui_ux', 'izleme'],
    durum: 'aktif', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'HO-02', kod_adi: 'ONARIM-BRAVO', takim_kodu: 'HO', asama: A, uzmanlik_alani: 'Hata Onarımı ve Düzeltme',
    gorev_tanimi: 'Tespit edilen hataları düzeltir, yama yapar',
    beceriler: ['hotfix', 'patch_yonetimi', 'regresyon_onleme', 'kod_duzeltme', 'yama_uygulama', 'hata_giderme', 'acil_mudahale', 'duzeltme_dogrulama'],
    kapsam_siniri: ['tasarim', 'deployment', 'hukuk', 'maliyet', 'gereksinim', 'risk', 'ui_ux', 'izleme'],
    durum: 'aktif', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'HO-03', kod_adi: 'ONARIM-CHARLIE', takim_kodu: 'HO', asama: A, uzmanlik_alani: 'Hata Onarımı ve Düzeltme',
    gorev_tanimi: 'Tespit edilen hataları düzeltir, yama yapar',
    beceriler: ['hotfix', 'patch_yonetimi', 'regresyon_onleme', 'kod_duzeltme', 'yama_uygulama', 'hata_giderme', 'acil_mudahale', 'duzeltme_dogrulama'],
    kapsam_siniri: ['tasarim', 'deployment', 'hukuk', 'maliyet', 'gereksinim', 'risk', 'ui_ux', 'izleme'],
    durum: 'aktif', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'HO-04', kod_adi: 'ONARIM-DELTA', takim_kodu: 'HO', asama: A, uzmanlik_alani: 'Hata Onarımı ve Düzeltme',
    gorev_tanimi: 'Tespit edilen hataları düzeltir, yama yapar',
    beceriler: ['hotfix', 'patch_yonetimi', 'regresyon_onleme', 'kod_duzeltme', 'yama_uygulama', 'hata_giderme', 'acil_mudahale', 'duzeltme_dogrulama'],
    kapsam_siniri: ['tasarim', 'deployment', 'hukuk', 'maliyet', 'gereksinim', 'risk', 'ui_ux', 'izleme'],
    durum: 'aktif', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'HO-05', kod_adi: 'ONARIM-ECHO', takim_kodu: 'HO', asama: A, uzmanlik_alani: 'Hata Onarımı ve Düzeltme',
    gorev_tanimi: 'Tespit edilen hataları düzeltir, yama yapar',
    beceriler: ['hotfix', 'patch_yonetimi', 'regresyon_onleme', 'kod_duzeltme', 'yama_uygulama', 'hata_giderme', 'acil_mudahale', 'duzeltme_dogrulama'],
    kapsam_siniri: ['tasarim', 'deployment', 'hukuk', 'maliyet', 'gereksinim', 'risk', 'ui_ux', 'izleme'],
    durum: 'aktif', tamamlanan_gorev: 0, hata_sayisi: 0 },

  // ── DK: DOKÜMANTASYON ───────────────────────────────────────
  { id: 'DK-01', kod_adi: 'DOKÜMAN-ALFA', takim_kodu: 'DK', asama: A, uzmanlik_alani: 'Dokümantasyon',
    gorev_tanimi: 'Her şeyi yazılı hale getirir — teknik, kullanıcı ve operasyon belgeleri',
    beceriler: ['teknik_yazarlik', 'api_dokumantasyonu', 'kullanici_kilavuzu', 'wiki_yonetimi', 'readme_yazimi', 'degisiklik_gunlugu', 'sema_belgeleme', 'operasyon_dokumani'],
    kapsam_siniri: ['kod_yazma', 'tasarim', 'test', 'deployment', 'hukuk', 'maliyet', 'gereksinim', 'izleme'],
    durum: 'aktif', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'DK-02', kod_adi: 'DOKÜMAN-BRAVO', takim_kodu: 'DK', asama: A, uzmanlik_alani: 'Dokümantasyon',
    gorev_tanimi: 'Her şeyi yazılı hale getirir — teknik, kullanıcı ve operasyon belgeleri',
    beceriler: ['teknik_yazarlik', 'api_dokumantasyonu', 'kullanici_kilavuzu', 'wiki_yonetimi', 'readme_yazimi', 'degisiklik_gunlugu', 'sema_belgeleme', 'operasyon_dokumani'],
    kapsam_siniri: ['kod_yazma', 'tasarim', 'test', 'deployment', 'hukuk', 'maliyet', 'gereksinim', 'izleme'],
    durum: 'aktif', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'DK-03', kod_adi: 'DOKÜMAN-CHARLIE', takim_kodu: 'DK', asama: A, uzmanlik_alani: 'Dokümantasyon',
    gorev_tanimi: 'Her şeyi yazılı hale getirir — teknik, kullanıcı ve operasyon belgeleri',
    beceriler: ['teknik_yazarlik', 'api_dokumantasyonu', 'kullanici_kilavuzu', 'wiki_yonetimi', 'readme_yazimi', 'degisiklik_gunlugu', 'sema_belgeleme', 'operasyon_dokumani'],
    kapsam_siniri: ['kod_yazma', 'tasarim', 'test', 'deployment', 'hukuk', 'maliyet', 'gereksinim', 'izleme'],
    durum: 'aktif', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'DK-04', kod_adi: 'DOKÜMAN-DELTA', takim_kodu: 'DK', asama: A, uzmanlik_alani: 'Dokümantasyon',
    gorev_tanimi: 'Her şeyi yazılı hale getirir — teknik, kullanıcı ve operasyon belgeleri',
    beceriler: ['teknik_yazarlik', 'api_dokumantasyonu', 'kullanici_kilavuzu', 'wiki_yonetimi', 'readme_yazimi', 'degisiklik_gunlugu', 'sema_belgeleme', 'operasyon_dokumani'],
    kapsam_siniri: ['kod_yazma', 'tasarim', 'test', 'deployment', 'hukuk', 'maliyet', 'gereksinim', 'izleme'],
    durum: 'aktif', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'DK-05', kod_adi: 'DOKÜMAN-ECHO', takim_kodu: 'DK', asama: A, uzmanlik_alani: 'Dokümantasyon',
    gorev_tanimi: 'Her şeyi yazılı hale getirir — teknik, kullanıcı ve operasyon belgeleri',
    beceriler: ['teknik_yazarlik', 'api_dokumantasyonu', 'kullanici_kilavuzu', 'wiki_yonetimi', 'readme_yazimi', 'degisiklik_gunlugu', 'sema_belgeleme', 'operasyon_dokumani'],
    kapsam_siniri: ['kod_yazma', 'tasarim', 'test', 'deployment', 'hukuk', 'maliyet', 'gereksinim', 'izleme'],
    durum: 'aktif', tamamlanan_gorev: 0, hata_sayisi: 0 },

  // ── EA: EĞİTİM VE KULLANICI ADAPTASYONU ────────────────────
  { id: 'EA-01', kod_adi: 'EĞİTİM-ALFA', takim_kodu: 'EA', asama: A, uzmanlik_alani: 'Eğitim ve Kullanıcı Adaptasyonu',
    gorev_tanimi: 'Kullanıcılara sistemi öğretir, geçiş sürecini yönetir',
    beceriler: ['egitim_materyali', 'kullanici_onboarding', 'degisim_yonetimi', 'tutorial_uretme', 'pratik_rehber', 'gecis_planlama', 'adaptasyon_izleme', 'geri_bildirim'],
    kapsam_siniri: ['kod_yazma', 'tasarim', 'test', 'deployment', 'hukuk', 'maliyet', 'gereksinim', 'izleme'],
    durum: 'aktif', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'EA-02', kod_adi: 'EĞİTİM-BRAVO', takim_kodu: 'EA', asama: A, uzmanlik_alani: 'Eğitim ve Kullanıcı Adaptasyonu',
    gorev_tanimi: 'Kullanıcılara sistemi öğretir, geçiş sürecini yönetir',
    beceriler: ['egitim_materyali', 'kullanici_onboarding', 'degisim_yonetimi', 'tutorial_uretme', 'pratik_rehber', 'gecis_planlama', 'adaptasyon_izleme', 'geri_bildirim'],
    kapsam_siniri: ['kod_yazma', 'tasarim', 'test', 'deployment', 'hukuk', 'maliyet', 'gereksinim', 'izleme'],
    durum: 'aktif', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'EA-03', kod_adi: 'EĞİTİM-CHARLIE', takim_kodu: 'EA', asama: A, uzmanlik_alani: 'Eğitim ve Kullanıcı Adaptasyonu',
    gorev_tanimi: 'Kullanıcılara sistemi öğretir, geçiş sürecini yönetir',
    beceriler: ['egitim_materyali', 'kullanici_onboarding', 'degisim_yonetimi', 'tutorial_uretme', 'pratik_rehber', 'gecis_planlama', 'adaptasyon_izleme', 'geri_bildirim'],
    kapsam_siniri: ['kod_yazma', 'tasarim', 'test', 'deployment', 'hukuk', 'maliyet', 'gereksinim', 'izleme'],
    durum: 'aktif', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'EA-04', kod_adi: 'EĞİTİM-DELTA', takim_kodu: 'EA', asama: A, uzmanlik_alani: 'Eğitim ve Kullanıcı Adaptasyonu',
    gorev_tanimi: 'Kullanıcılara sistemi öğretir, geçiş sürecini yönetir',
    beceriler: ['egitim_materyali', 'kullanici_onboarding', 'degisim_yonetimi', 'tutorial_uretme', 'pratik_rehber', 'gecis_planlama', 'adaptasyon_izleme', 'geri_bildirim'],
    kapsam_siniri: ['kod_yazma', 'tasarim', 'test', 'deployment', 'hukuk', 'maliyet', 'gereksinim', 'izleme'],
    durum: 'aktif', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'EA-05', kod_adi: 'EĞİTİM-ECHO', takim_kodu: 'EA', asama: A, uzmanlik_alani: 'Eğitim ve Kullanıcı Adaptasyonu',
    gorev_tanimi: 'Kullanıcılara sistemi öğretir, geçiş sürecini yönetir',
    beceriler: ['egitim_materyali', 'kullanici_onboarding', 'degisim_yonetimi', 'tutorial_uretme', 'pratik_rehber', 'gecis_planlama', 'adaptasyon_izleme', 'geri_bildirim'],
    kapsam_siniri: ['kod_yazma', 'tasarim', 'test', 'deployment', 'hukuk', 'maliyet', 'gereksinim', 'izleme'],
    durum: 'aktif', tamamlanan_gorev: 0, hata_sayisi: 0 },
];

module.exports = { YASATMA };
