// ============================================================
// AŞAMA 2: TASARIM — 6 Takım × 5 Ajan = 30 Birim
// ============================================================
const { ASAMALAR } = require('./types');
const A = ASAMALAR.TASARIM;

const TASARIM = [

  // ── MT: MİMARİ TASARIM ──────────────────────────────────────
  { id: 'MT-01', kod_adi: 'MİMARİ-ALFA', takim_kodu: 'MT', asama: A, uzmanlik_alani: 'Mimari Tasarım',
    gorev_tanimi: 'Yazılımın iskeletini çizer — monolith/microservice, katmanlar, bileşen yapısı',
    beceriler: ['yazilim_mimarileri', 'tasarim_kaliplari', 'solid_prensipleri', 'sistem_tasarimi', 'monolith', 'microservice', 'katman_mimarisi', 'bilesen_yapisi'],
    kapsam_siniri: ['kod_yazma', 'test', 'deployment', 'veritabani_islemleri', 'izleme', 'dokumantasyon', 'hukuk', 'maliyet'],
    durum: 'aktif', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'MT-02', kod_adi: 'MİMARİ-BRAVO', takim_kodu: 'MT', asama: A, uzmanlik_alani: 'Mimari Tasarım',
    gorev_tanimi: 'Yazılımın iskeletini çizer — monolith/microservice, katmanlar, bileşen yapısı',
    beceriler: ['yazilim_mimarileri', 'tasarim_kaliplari', 'solid_prensipleri', 'sistem_tasarimi', 'monolith', 'microservice', 'katman_mimarisi', 'bilesen_yapisi'],
    kapsam_siniri: ['kod_yazma', 'test', 'deployment', 'veritabani_islemleri', 'izleme', 'dokumantasyon', 'hukuk', 'maliyet'],
    durum: 'aktif', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'MT-03', kod_adi: 'MİMARİ-CHARLIE', takim_kodu: 'MT', asama: A, uzmanlik_alani: 'Mimari Tasarım',
    gorev_tanimi: 'Yazılımın iskeletini çizer — monolith/microservice, katmanlar, bileşen yapısı',
    beceriler: ['yazilim_mimarileri', 'tasarim_kaliplari', 'solid_prensipleri', 'sistem_tasarimi', 'monolith', 'microservice', 'katman_mimarisi', 'bilesen_yapisi'],
    kapsam_siniri: ['kod_yazma', 'test', 'deployment', 'veritabani_islemleri', 'izleme', 'dokumantasyon', 'hukuk', 'maliyet'],
    durum: 'aktif', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'MT-04', kod_adi: 'MİMARİ-DELTA', takim_kodu: 'MT', asama: A, uzmanlik_alani: 'Mimari Tasarım',
    gorev_tanimi: 'Yazılımın iskeletini çizer — monolith/microservice, katmanlar, bileşen yapısı',
    beceriler: ['yazilim_mimarileri', 'tasarim_kaliplari', 'solid_prensipleri', 'sistem_tasarimi', 'monolith', 'microservice', 'katman_mimarisi', 'bilesen_yapisi'],
    kapsam_siniri: ['kod_yazma', 'test', 'deployment', 'veritabani_islemleri', 'izleme', 'dokumantasyon', 'hukuk', 'maliyet'],
    durum: 'aktif', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'MT-05', kod_adi: 'MİMARİ-ECHO', takim_kodu: 'MT', asama: A, uzmanlik_alani: 'Mimari Tasarım',
    gorev_tanimi: 'Yazılımın iskeletini çizer — monolith/microservice, katmanlar, bileşen yapısı',
    beceriler: ['yazilim_mimarileri', 'tasarim_kaliplari', 'solid_prensipleri', 'sistem_tasarimi', 'monolith', 'microservice', 'katman_mimarisi', 'bilesen_yapisi'],
    kapsam_siniri: ['kod_yazma', 'test', 'deployment', 'veritabani_islemleri', 'izleme', 'dokumantasyon', 'hukuk', 'maliyet'],
    durum: 'aktif', tamamlanan_gorev: 0, hata_sayisi: 0 },

  // ── AT: ALTYAPI TASARIMI ────────────────────────────────────
  { id: 'AT-01', kod_adi: 'ALTYAPI-ALFA', takim_kodu: 'AT', asama: A, uzmanlik_alani: 'Altyapı Tasarımı',
    gorev_tanimi: 'Sistemin nerede ve nasıl çalışacağını planlar — sunucu, ağ, cloud',
    beceriler: ['sunucu_yonetimi', 'cloud_platformlari', 'aws', 'azure', 'gcp', 'ag_topolojisi', 'load_balancing', 'cdn'],
    kapsam_siniri: ['kod_yazma', 'test', 'ui_ux', 'hukuk', 'maliyet', 'dokumantasyon', 'egitim', 'gereksinim'],
    durum: 'aktif', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'AT-02', kod_adi: 'ALTYAPI-BRAVO', takim_kodu: 'AT', asama: A, uzmanlik_alani: 'Altyapı Tasarımı',
    gorev_tanimi: 'Sistemin nerede ve nasıl çalışacağını planlar — sunucu, ağ, cloud',
    beceriler: ['sunucu_yonetimi', 'cloud_platformlari', 'aws', 'azure', 'gcp', 'ag_topolojisi', 'load_balancing', 'cdn'],
    kapsam_siniri: ['kod_yazma', 'test', 'ui_ux', 'hukuk', 'maliyet', 'dokumantasyon', 'egitim', 'gereksinim'],
    durum: 'aktif', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'AT-03', kod_adi: 'ALTYAPI-CHARLIE', takim_kodu: 'AT', asama: A, uzmanlik_alani: 'Altyapı Tasarımı',
    gorev_tanimi: 'Sistemin nerede ve nasıl çalışacağını planlar — sunucu, ağ, cloud',
    beceriler: ['sunucu_yonetimi', 'cloud_platformlari', 'aws', 'azure', 'gcp', 'ag_topolojisi', 'load_balancing', 'cdn'],
    kapsam_siniri: ['kod_yazma', 'test', 'ui_ux', 'hukuk', 'maliyet', 'dokumantasyon', 'egitim', 'gereksinim'],
    durum: 'aktif', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'AT-04', kod_adi: 'ALTYAPI-DELTA', takim_kodu: 'AT', asama: A, uzmanlik_alani: 'Altyapı Tasarımı',
    gorev_tanimi: 'Sistemin nerede ve nasıl çalışacağını planlar — sunucu, ağ, cloud',
    beceriler: ['sunucu_yonetimi', 'cloud_platformlari', 'aws', 'azure', 'gcp', 'ag_topolojisi', 'load_balancing', 'cdn'],
    kapsam_siniri: ['kod_yazma', 'test', 'ui_ux', 'hukuk', 'maliyet', 'dokumantasyon', 'egitim', 'gereksinim'],
    durum: 'aktif', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'AT-05', kod_adi: 'ALTYAPI-ECHO', takim_kodu: 'AT', asama: A, uzmanlik_alani: 'Altyapı Tasarımı',
    gorev_tanimi: 'Sistemin nerede ve nasıl çalışacağını planlar — sunucu, ağ, cloud',
    beceriler: ['sunucu_yonetimi', 'cloud_platformlari', 'aws', 'azure', 'gcp', 'ag_topolojisi', 'load_balancing', 'cdn'],
    kapsam_siniri: ['kod_yazma', 'test', 'ui_ux', 'hukuk', 'maliyet', 'dokumantasyon', 'egitim', 'gereksinim'],
    durum: 'aktif', tamamlanan_gorev: 0, hata_sayisi: 0 },

  // ── VM: VERİ MODELLEME ──────────────────────────────────────
  { id: 'VM-01', kod_adi: 'VERİMODEL-ALFA', takim_kodu: 'VM', asama: A, uzmanlik_alani: 'Veri Modelleme',
    gorev_tanimi: 'Veritabanı tablolarını, ilişkileri, indeksleri, şemaları tasarlar',
    beceriler: ['iliskisel_veritabani', 'nosql', 'normalizasyon', 'er_diyagramlari', 'indeks_stratejisi', 'sema_tasarimi', 'veri_iliskileri', 'tablo_yapisi'],
    kapsam_siniri: ['kod_yazma', 'test', 'deployment', 'ui_ux', 'hukuk', 'izleme', 'egitim', 'performans_test'],
    durum: 'aktif', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'VM-02', kod_adi: 'VERİMODEL-BRAVO', takim_kodu: 'VM', asama: A, uzmanlik_alani: 'Veri Modelleme',
    gorev_tanimi: 'Veritabanı tablolarını, ilişkileri, indeksleri, şemaları tasarlar',
    beceriler: ['iliskisel_veritabani', 'nosql', 'normalizasyon', 'er_diyagramlari', 'indeks_stratejisi', 'sema_tasarimi', 'veri_iliskileri', 'tablo_yapisi'],
    kapsam_siniri: ['kod_yazma', 'test', 'deployment', 'ui_ux', 'hukuk', 'izleme', 'egitim', 'performans_test'],
    durum: 'aktif', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'VM-03', kod_adi: 'VERİMODEL-CHARLIE', takim_kodu: 'VM', asama: A, uzmanlik_alani: 'Veri Modelleme',
    gorev_tanimi: 'Veritabanı tablolarını, ilişkileri, indeksleri, şemaları tasarlar',
    beceriler: ['iliskisel_veritabani', 'nosql', 'normalizasyon', 'er_diyagramlari', 'indeks_stratejisi', 'sema_tasarimi', 'veri_iliskileri', 'tablo_yapisi'],
    kapsam_siniri: ['kod_yazma', 'test', 'deployment', 'ui_ux', 'hukuk', 'izleme', 'egitim', 'performans_test'],
    durum: 'aktif', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'VM-04', kod_adi: 'VERİMODEL-DELTA', takim_kodu: 'VM', asama: A, uzmanlik_alani: 'Veri Modelleme',
    gorev_tanimi: 'Veritabanı tablolarını, ilişkileri, indeksleri, şemaları tasarlar',
    beceriler: ['iliskisel_veritabani', 'nosql', 'normalizasyon', 'er_diyagramlari', 'indeks_stratejisi', 'sema_tasarimi', 'veri_iliskileri', 'tablo_yapisi'],
    kapsam_siniri: ['kod_yazma', 'test', 'deployment', 'ui_ux', 'hukuk', 'izleme', 'egitim', 'performans_test'],
    durum: 'aktif', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'VM-05', kod_adi: 'VERİMODEL-ECHO', takim_kodu: 'VM', asama: A, uzmanlik_alani: 'Veri Modelleme',
    gorev_tanimi: 'Veritabanı tablolarını, ilişkileri, indeksleri, şemaları tasarlar',
    beceriler: ['iliskisel_veritabani', 'nosql', 'normalizasyon', 'er_diyagramlari', 'indeks_stratejisi', 'sema_tasarimi', 'veri_iliskileri', 'tablo_yapisi'],
    kapsam_siniri: ['kod_yazma', 'test', 'deployment', 'ui_ux', 'hukuk', 'izleme', 'egitim', 'performans_test'],
    durum: 'aktif', tamamlanan_gorev: 0, hata_sayisi: 0 },

  // ── AP: API TASARIMI ────────────────────────────────────────
  { id: 'AP-01', kod_adi: 'API-ALFA', takim_kodu: 'AP', asama: A, uzmanlik_alani: 'API Tasarımı',
    gorev_tanimi: 'Sistemler arası kontratları tanımlar — endpoint, versiyon, format',
    beceriler: ['rest_api', 'graphql', 'grpc', 'api_versiyonlama', 'rate_limiting', 'openapi', 'swagger', 'endpoint_tasarimi'],
    kapsam_siniri: ['kod_yazma', 'test', 'deployment', 'ui_ux', 'hukuk', 'izleme', 'egitim', 'maliyet'],
    durum: 'aktif', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'AP-02', kod_adi: 'API-BRAVO', takim_kodu: 'AP', asama: A, uzmanlik_alani: 'API Tasarımı',
    gorev_tanimi: 'Sistemler arası kontratları tanımlar — endpoint, versiyon, format',
    beceriler: ['rest_api', 'graphql', 'grpc', 'api_versiyonlama', 'rate_limiting', 'openapi', 'swagger', 'endpoint_tasarimi'],
    kapsam_siniri: ['kod_yazma', 'test', 'deployment', 'ui_ux', 'hukuk', 'izleme', 'egitim', 'maliyet'],
    durum: 'aktif', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'AP-03', kod_adi: 'API-CHARLIE', takim_kodu: 'AP', asama: A, uzmanlik_alani: 'API Tasarımı',
    gorev_tanimi: 'Sistemler arası kontratları tanımlar — endpoint, versiyon, format',
    beceriler: ['rest_api', 'graphql', 'grpc', 'api_versiyonlama', 'rate_limiting', 'openapi', 'swagger', 'endpoint_tasarimi'],
    kapsam_siniri: ['kod_yazma', 'test', 'deployment', 'ui_ux', 'hukuk', 'izleme', 'egitim', 'maliyet'],
    durum: 'aktif', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'AP-04', kod_adi: 'API-DELTA', takim_kodu: 'AP', asama: A, uzmanlik_alani: 'API Tasarımı',
    gorev_tanimi: 'Sistemler arası kontratları tanımlar — endpoint, versiyon, format',
    beceriler: ['rest_api', 'graphql', 'grpc', 'api_versiyonlama', 'rate_limiting', 'openapi', 'swagger', 'endpoint_tasarimi'],
    kapsam_siniri: ['kod_yazma', 'test', 'deployment', 'ui_ux', 'hukuk', 'izleme', 'egitim', 'maliyet'],
    durum: 'aktif', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'AP-05', kod_adi: 'API-ECHO', takim_kodu: 'AP', asama: A, uzmanlik_alani: 'API Tasarımı',
    gorev_tanimi: 'Sistemler arası kontratları tanımlar — endpoint, versiyon, format',
    beceriler: ['rest_api', 'graphql', 'grpc', 'api_versiyonlama', 'rate_limiting', 'openapi', 'swagger', 'endpoint_tasarimi'],
    kapsam_siniri: ['kod_yazma', 'test', 'deployment', 'ui_ux', 'hukuk', 'izleme', 'egitim', 'maliyet'],
    durum: 'aktif', tamamlanan_gorev: 0, hata_sayisi: 0 },

  // ── GT: GÜVENLİK TASARIMI ──────────────────────────────────
  { id: 'GT-01', kod_adi: 'GÜVTASARIM-ALFA', takim_kodu: 'GT', asama: A, uzmanlik_alani: 'Güvenlik Tasarımı',
    gorev_tanimi: 'Kimlik doğrulama, yetkilendirme, şifreleme, ağ güvenliğini tasarlar',
    beceriler: ['oauth', 'jwt', 'rbac', 'sifreleme_algoritmalari', 'guvenlik_mimarisi', 'kimlik_dogrulama', 'yetkilendirme', 'ag_guvenligi'],
    kapsam_siniri: ['kod_yazma', 'test', 'deployment', 'ui_ux', 'hukuk', 'maliyet', 'dokumantasyon', 'egitim'],
    durum: 'aktif', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'GT-02', kod_adi: 'GÜVTASARIM-BRAVO', takim_kodu: 'GT', asama: A, uzmanlik_alani: 'Güvenlik Tasarımı',
    gorev_tanimi: 'Kimlik doğrulama, yetkilendirme, şifreleme, ağ güvenliğini tasarlar',
    beceriler: ['oauth', 'jwt', 'rbac', 'sifreleme_algoritmalari', 'guvenlik_mimarisi', 'kimlik_dogrulama', 'yetkilendirme', 'ag_guvenligi'],
    kapsam_siniri: ['kod_yazma', 'test', 'deployment', 'ui_ux', 'hukuk', 'maliyet', 'dokumantasyon', 'egitim'],
    durum: 'aktif', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'GT-03', kod_adi: 'GÜVTASARIM-CHARLIE', takim_kodu: 'GT', asama: A, uzmanlik_alani: 'Güvenlik Tasarımı',
    gorev_tanimi: 'Kimlik doğrulama, yetkilendirme, şifreleme, ağ güvenliğini tasarlar',
    beceriler: ['oauth', 'jwt', 'rbac', 'sifreleme_algoritmalari', 'guvenlik_mimarisi', 'kimlik_dogrulama', 'yetkilendirme', 'ag_guvenligi'],
    kapsam_siniri: ['kod_yazma', 'test', 'deployment', 'ui_ux', 'hukuk', 'maliyet', 'dokumantasyon', 'egitim'],
    durum: 'aktif', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'GT-04', kod_adi: 'GÜVTASARIM-DELTA', takim_kodu: 'GT', asama: A, uzmanlik_alani: 'Güvenlik Tasarımı',
    gorev_tanimi: 'Kimlik doğrulama, yetkilendirme, şifreleme, ağ güvenliğini tasarlar',
    beceriler: ['oauth', 'jwt', 'rbac', 'sifreleme_algoritmalari', 'guvenlik_mimarisi', 'kimlik_dogrulama', 'yetkilendirme', 'ag_guvenligi'],
    kapsam_siniri: ['kod_yazma', 'test', 'deployment', 'ui_ux', 'hukuk', 'maliyet', 'dokumantasyon', 'egitim'],
    durum: 'aktif', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'GT-05', kod_adi: 'GÜVTASARIM-ECHO', takim_kodu: 'GT', asama: A, uzmanlik_alani: 'Güvenlik Tasarımı',
    gorev_tanimi: 'Kimlik doğrulama, yetkilendirme, şifreleme, ağ güvenliğini tasarlar',
    beceriler: ['oauth', 'jwt', 'rbac', 'sifreleme_algoritmalari', 'guvenlik_mimarisi', 'kimlik_dogrulama', 'yetkilendirme', 'ag_guvenligi'],
    kapsam_siniri: ['kod_yazma', 'test', 'deployment', 'ui_ux', 'hukuk', 'maliyet', 'dokumantasyon', 'egitim'],
    durum: 'aktif', tamamlanan_gorev: 0, hata_sayisi: 0 },

  // ── UX: KULLANICI DENEYİMİ ─────────────────────────────────
  { id: 'UX-01', kod_adi: 'KULLANICI-ALFA', takim_kodu: 'UX', asama: A, uzmanlik_alani: 'Kullanıcı Deneyimi (UI/UX)',
    gorev_tanimi: 'Arayüzü tasarlar, kullanım kolaylığını sağlar, kullanıcı akışlarını çizer',
    beceriler: ['wireframe', 'kullanici_arastirmasi', 'etkilesim_tasarimi', 'gorsel_hiyerarsi', 'responsive_tasarim', 'kullanici_akislari', 'prototipleme', 'kullanilabilirlik'],
    kapsam_siniri: ['kod_yazma', 'test', 'deployment', 'veritabani', 'guvenlik', 'hukuk', 'maliyet', 'izleme'],
    durum: 'aktif', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'UX-02', kod_adi: 'KULLANICI-BRAVO', takim_kodu: 'UX', asama: A, uzmanlik_alani: 'Kullanıcı Deneyimi (UI/UX)',
    gorev_tanimi: 'Arayüzü tasarlar, kullanım kolaylığını sağlar, kullanıcı akışlarını çizer',
    beceriler: ['wireframe', 'kullanici_arastirmasi', 'etkilesim_tasarimi', 'gorsel_hiyerarsi', 'responsive_tasarim', 'kullanici_akislari', 'prototipleme', 'kullanilabilirlik'],
    kapsam_siniri: ['kod_yazma', 'test', 'deployment', 'veritabani', 'guvenlik', 'hukuk', 'maliyet', 'izleme'],
    durum: 'aktif', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'UX-03', kod_adi: 'KULLANICI-CHARLIE', takim_kodu: 'UX', asama: A, uzmanlik_alani: 'Kullanıcı Deneyimi (UI/UX)',
    gorev_tanimi: 'Arayüzü tasarlar, kullanım kolaylığını sağlar, kullanıcı akışlarını çizer',
    beceriler: ['wireframe', 'kullanici_arastirmasi', 'etkilesim_tasarimi', 'gorsel_hiyerarsi', 'responsive_tasarim', 'kullanici_akislari', 'prototipleme', 'kullanilabilirlik'],
    kapsam_siniri: ['kod_yazma', 'test', 'deployment', 'veritabani', 'guvenlik', 'hukuk', 'maliyet', 'izleme'],
    durum: 'aktif', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'UX-04', kod_adi: 'KULLANICI-DELTA', takim_kodu: 'UX', asama: A, uzmanlik_alani: 'Kullanıcı Deneyimi (UI/UX)',
    gorev_tanimi: 'Arayüzü tasarlar, kullanım kolaylığını sağlar, kullanıcı akışlarını çizer',
    beceriler: ['wireframe', 'kullanici_arastirmasi', 'etkilesim_tasarimi', 'gorsel_hiyerarsi', 'responsive_tasarim', 'kullanici_akislari', 'prototipleme', 'kullanilabilirlik'],
    kapsam_siniri: ['kod_yazma', 'test', 'deployment', 'veritabani', 'guvenlik', 'hukuk', 'maliyet', 'izleme'],
    durum: 'aktif', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'UX-05', kod_adi: 'KULLANICI-ECHO', takim_kodu: 'UX', asama: A, uzmanlik_alani: 'Kullanıcı Deneyimi (UI/UX)',
    gorev_tanimi: 'Arayüzü tasarlar, kullanım kolaylığını sağlar, kullanıcı akışlarını çizer',
    beceriler: ['wireframe', 'kullanici_arastirmasi', 'etkilesim_tasarimi', 'gorsel_hiyerarsi', 'responsive_tasarim', 'kullanici_akislari', 'prototipleme', 'kullanilabilirlik'],
    kapsam_siniri: ['kod_yazma', 'test', 'deployment', 'veritabani', 'guvenlik', 'hukuk', 'maliyet', 'izleme'],
    durum: 'aktif', tamamlanan_gorev: 0, hata_sayisi: 0 },
];

module.exports = { TASARIM };
