// ============================================================
// AŞAMA 1: YAPIM ÖNCESİ — 5 Takım × 5 Ajan = 25 Birim
// ============================================================
const { ASAMALAR } = require('./types');
const A = ASAMALAR.YAPIM_ONCESI;

const YAPIM_ONCESI = [

  // ── GA: GEREKSİNİM ANALİZİ ─────────────────────────────────
  { id: 'GA-01', kod_adi: 'GEREKSİNİM-ALFA', takim_kodu: 'GA', asama: A,
    uzmanlik_alani: 'Gereksinim Analizi',
    gorev_tanimi: 'Görevin ne istediğini parçalar, kullanıcıyı tanımlar, fonksiyonel ve fonksiyonel olmayan gereksinimleri çıkarır',
    beceriler: ['is_analizi', 'kullanici_hikayeleri', 'kapsam_belirleme', 'kabul_kriterleri', 'fonksiyonel_gereksinim', 'fonksiyonel_olmayan_gereksinim', 'kullanici_tanimlama', 'gereksinim_parcalama'],
    kapsam_siniri: ['kod_yazma', 'tasarim', 'test', 'deployment', 'veritabani', 'guvenlik', 'izleme', 'dokumantasyon'],
    durum: 'HAZIR', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'GA-02', kod_adi: 'GEREKSİNİM-BRAVO', takim_kodu: 'GA', asama: A,
    uzmanlik_alani: 'Gereksinim Analizi',
    gorev_tanimi: 'Görevin ne istediğini parçalar, kullanıcıyı tanımlar, fonksiyonel ve fonksiyonel olmayan gereksinimleri çıkarır',
    beceriler: ['is_analizi', 'kullanici_hikayeleri', 'kapsam_belirleme', 'kabul_kriterleri', 'fonksiyonel_gereksinim', 'fonksiyonel_olmayan_gereksinim', 'kullanici_tanimlama', 'gereksinim_parcalama'],
    kapsam_siniri: ['kod_yazma', 'tasarim', 'test', 'deployment', 'veritabani', 'guvenlik', 'izleme', 'dokumantasyon'],
    durum: 'HAZIR', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'GA-03', kod_adi: 'GEREKSİNİM-CHARLIE', takim_kodu: 'GA', asama: A,
    uzmanlik_alani: 'Gereksinim Analizi',
    gorev_tanimi: 'Görevin ne istediğini parçalar, kullanıcıyı tanımlar, fonksiyonel ve fonksiyonel olmayan gereksinimleri çıkarır',
    beceriler: ['is_analizi', 'kullanici_hikayeleri', 'kapsam_belirleme', 'kabul_kriterleri', 'fonksiyonel_gereksinim', 'fonksiyonel_olmayan_gereksinim', 'kullanici_tanimlama', 'gereksinim_parcalama'],
    kapsam_siniri: ['kod_yazma', 'tasarim', 'test', 'deployment', 'veritabani', 'guvenlik', 'izleme', 'dokumantasyon'],
    durum: 'HAZIR', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'GA-04', kod_adi: 'GEREKSİNİM-DELTA', takim_kodu: 'GA', asama: A,
    uzmanlik_alani: 'Gereksinim Analizi',
    gorev_tanimi: 'Görevin ne istediğini parçalar, kullanıcıyı tanımlar, fonksiyonel ve fonksiyonel olmayan gereksinimleri çıkarır',
    beceriler: ['is_analizi', 'kullanici_hikayeleri', 'kapsam_belirleme', 'kabul_kriterleri', 'fonksiyonel_gereksinim', 'fonksiyonel_olmayan_gereksinim', 'kullanici_tanimlama', 'gereksinim_parcalama'],
    kapsam_siniri: ['kod_yazma', 'tasarim', 'test', 'deployment', 'veritabani', 'guvenlik', 'izleme', 'dokumantasyon'],
    durum: 'HAZIR', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'GA-05', kod_adi: 'GEREKSİNİM-ECHO', takim_kodu: 'GA', asama: A,
    uzmanlik_alani: 'Gereksinim Analizi',
    gorev_tanimi: 'Görevin ne istediğini parçalar, kullanıcıyı tanımlar, fonksiyonel ve fonksiyonel olmayan gereksinimleri çıkarır',
    beceriler: ['is_analizi', 'kullanici_hikayeleri', 'kapsam_belirleme', 'kabul_kriterleri', 'fonksiyonel_gereksinim', 'fonksiyonel_olmayan_gereksinim', 'kullanici_tanimlama', 'gereksinim_parcalama'],
    kapsam_siniri: ['kod_yazma', 'tasarim', 'test', 'deployment', 'veritabani', 'guvenlik', 'izleme', 'dokumantasyon'],
    durum: 'HAZIR', tamamlanan_gorev: 0, hata_sayisi: 0 },

  // ── RA: RİSK ANALİZİ ───────────────────────────────────────
  { id: 'RA-01', kod_adi: 'RİSK-ALFA', takim_kodu: 'RA', asama: A,
    uzmanlik_alani: 'Risk Analizi',
    gorev_tanimi: 'Her kararın ya tutmazsa tarafını önceden tespit eder, alternatif senaryolar üretir',
    beceriler: ['risk_degerlendirme_matrisi', 'olasilik_etki_analizi', 'acil_durum_planlari', 'alternatif_senaryo', 'risk_tespiti', 'risk_onceliklendirme', 'risk_azaltma', 'erken_uyari'],
    kapsam_siniri: ['kod_yazma', 'tasarim', 'test', 'deployment', 'veritabani', 'guvenlik', 'izleme', 'dokumantasyon'],
    durum: 'HAZIR', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'RA-02', kod_adi: 'RİSK-BRAVO', takim_kodu: 'RA', asama: A,
    uzmanlik_alani: 'Risk Analizi',
    gorev_tanimi: 'Her kararın ya tutmazsa tarafını önceden tespit eder, alternatif senaryolar üretir',
    beceriler: ['risk_degerlendirme_matrisi', 'olasilik_etki_analizi', 'acil_durum_planlari', 'alternatif_senaryo', 'risk_tespiti', 'risk_onceliklendirme', 'risk_azaltma', 'erken_uyari'],
    kapsam_siniri: ['kod_yazma', 'tasarim', 'test', 'deployment', 'veritabani', 'guvenlik', 'izleme', 'dokumantasyon'],
    durum: 'HAZIR', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'RA-03', kod_adi: 'RİSK-CHARLIE', takim_kodu: 'RA', asama: A,
    uzmanlik_alani: 'Risk Analizi',
    gorev_tanimi: 'Her kararın ya tutmazsa tarafını önceden tespit eder, alternatif senaryolar üretir',
    beceriler: ['risk_degerlendirme_matrisi', 'olasilik_etki_analizi', 'acil_durum_planlari', 'alternatif_senaryo', 'risk_tespiti', 'risk_onceliklendirme', 'risk_azaltma', 'erken_uyari'],
    kapsam_siniri: ['kod_yazma', 'tasarim', 'test', 'deployment', 'veritabani', 'guvenlik', 'izleme', 'dokumantasyon'],
    durum: 'HAZIR', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'RA-04', kod_adi: 'RİSK-DELTA', takim_kodu: 'RA', asama: A,
    uzmanlik_alani: 'Risk Analizi',
    gorev_tanimi: 'Her kararın ya tutmazsa tarafını önceden tespit eder, alternatif senaryolar üretir',
    beceriler: ['risk_degerlendirme_matrisi', 'olasilik_etki_analizi', 'acil_durum_planlari', 'alternatif_senaryo', 'risk_tespiti', 'risk_onceliklendirme', 'risk_azaltma', 'erken_uyari'],
    kapsam_siniri: ['kod_yazma', 'tasarim', 'test', 'deployment', 'veritabani', 'guvenlik', 'izleme', 'dokumantasyon'],
    durum: 'HAZIR', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'RA-05', kod_adi: 'RİSK-ECHO', takim_kodu: 'RA', asama: A,
    uzmanlik_alani: 'Risk Analizi',
    gorev_tanimi: 'Her kararın ya tutmazsa tarafını önceden tespit eder, alternatif senaryolar üretir',
    beceriler: ['risk_degerlendirme_matrisi', 'olasilik_etki_analizi', 'acil_durum_planlari', 'alternatif_senaryo', 'risk_tespiti', 'risk_onceliklendirme', 'risk_azaltma', 'erken_uyari'],
    kapsam_siniri: ['kod_yazma', 'tasarim', 'test', 'deployment', 'veritabani', 'guvenlik', 'izleme', 'dokumantasyon'],
    durum: 'HAZIR', tamamlanan_gorev: 0, hata_sayisi: 0 },

  // ── HU: HUKUK VE UYUMLULUK ─────────────────────────────────
  { id: 'HU-01', kod_adi: 'HUKUK-ALFA', takim_kodu: 'HU', asama: A,
    uzmanlik_alani: 'Hukuk ve Uyumluluk',
    gorev_tanimi: 'Yasal kısıtları belirler — KVKK, lisans, veri yasaları, fikri mülkiyet',
    beceriler: ['veri_koruma_mevzuati', 'kvkk', 'gdpr', 'yazilim_lisanslama', 'duzenleyici_uyumluluk', 'fikri_mulkiyet', 'yasal_kisit_analizi', 'lisans_denetimi'],
    kapsam_siniri: ['kod_yazma', 'tasarim', 'test', 'deployment', 'veritabani', 'mimari', 'izleme', 'performans'],
    durum: 'HAZIR', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'HU-02', kod_adi: 'HUKUK-BRAVO', takim_kodu: 'HU', asama: A,
    uzmanlik_alani: 'Hukuk ve Uyumluluk',
    gorev_tanimi: 'Yasal kısıtları belirler — KVKK, lisans, veri yasaları, fikri mülkiyet',
    beceriler: ['veri_koruma_mevzuati', 'kvkk', 'gdpr', 'yazilim_lisanslama', 'duzenleyici_uyumluluk', 'fikri_mulkiyet', 'yasal_kisit_analizi', 'lisans_denetimi'],
    kapsam_siniri: ['kod_yazma', 'tasarim', 'test', 'deployment', 'veritabani', 'mimari', 'izleme', 'performans'],
    durum: 'HAZIR', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'HU-03', kod_adi: 'HUKUK-CHARLIE', takim_kodu: 'HU', asama: A,
    uzmanlik_alani: 'Hukuk ve Uyumluluk',
    gorev_tanimi: 'Yasal kısıtları belirler — KVKK, lisans, veri yasaları, fikri mülkiyet',
    beceriler: ['veri_koruma_mevzuati', 'kvkk', 'gdpr', 'yazilim_lisanslama', 'duzenleyici_uyumluluk', 'fikri_mulkiyet', 'yasal_kisit_analizi', 'lisans_denetimi'],
    kapsam_siniri: ['kod_yazma', 'tasarim', 'test', 'deployment', 'veritabani', 'mimari', 'izleme', 'performans'],
    durum: 'HAZIR', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'HU-04', kod_adi: 'HUKUK-DELTA', takim_kodu: 'HU', asama: A,
    uzmanlik_alani: 'Hukuk ve Uyumluluk',
    gorev_tanimi: 'Yasal kısıtları belirler — KVKK, lisans, veri yasaları, fikri mülkiyet',
    beceriler: ['veri_koruma_mevzuati', 'kvkk', 'gdpr', 'yazilim_lisanslama', 'duzenleyici_uyumluluk', 'fikri_mulkiyet', 'yasal_kisit_analizi', 'lisans_denetimi'],
    kapsam_siniri: ['kod_yazma', 'tasarim', 'test', 'deployment', 'veritabani', 'mimari', 'izleme', 'performans'],
    durum: 'HAZIR', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'HU-05', kod_adi: 'HUKUK-ECHO', takim_kodu: 'HU', asama: A,
    uzmanlik_alani: 'Hukuk ve Uyumluluk',
    gorev_tanimi: 'Yasal kısıtları belirler — KVKK, lisans, veri yasaları, fikri mülkiyet',
    beceriler: ['veri_koruma_mevzuati', 'kvkk', 'gdpr', 'yazilim_lisanslama', 'duzenleyici_uyumluluk', 'fikri_mulkiyet', 'yasal_kisit_analizi', 'lisans_denetimi'],
    kapsam_siniri: ['kod_yazma', 'tasarim', 'test', 'deployment', 'veritabani', 'mimari', 'izleme', 'performans'],
    durum: 'HAZIR', tamamlanan_gorev: 0, hata_sayisi: 0 },

  // ── MK: MALİYET VE KAYNAK ──────────────────────────────────
  { id: 'MK-01', kod_adi: 'MALİYET-ALFA', takim_kodu: 'MK', asama: A,
    uzmanlik_alani: 'Maliyet ve Kaynak',
    gorev_tanimi: 'Bütçe hesaplar, gerekli insan/makine kaynaklarını belirler',
    beceriler: ['maliyet_tahmini', 'kaynak_planlama', 'butce_yonetimi', 'roi_hesaplama', 'kaynak_dagitimi', 'maliyet_optimizasyon', 'insan_kaynak_planlama', 'makine_kaynak_planlama'],
    kapsam_siniri: ['kod_yazma', 'tasarim', 'test', 'deployment', 'veritabani', 'guvenlik', 'izleme', 'dokumantasyon'],
    durum: 'HAZIR', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'MK-02', kod_adi: 'MALİYET-BRAVO', takim_kodu: 'MK', asama: A,
    uzmanlik_alani: 'Maliyet ve Kaynak',
    gorev_tanimi: 'Bütçe hesaplar, gerekli insan/makine kaynaklarını belirler',
    beceriler: ['maliyet_tahmini', 'kaynak_planlama', 'butce_yonetimi', 'roi_hesaplama', 'kaynak_dagitimi', 'maliyet_optimizasyon', 'insan_kaynak_planlama', 'makine_kaynak_planlama'],
    kapsam_siniri: ['kod_yazma', 'tasarim', 'test', 'deployment', 'veritabani', 'guvenlik', 'izleme', 'dokumantasyon'],
    durum: 'HAZIR', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'MK-03', kod_adi: 'MALİYET-CHARLIE', takim_kodu: 'MK', asama: A,
    uzmanlik_alani: 'Maliyet ve Kaynak',
    gorev_tanimi: 'Bütçe hesaplar, gerekli insan/makine kaynaklarını belirler',
    beceriler: ['maliyet_tahmini', 'kaynak_planlama', 'butce_yonetimi', 'roi_hesaplama', 'kaynak_dagitimi', 'maliyet_optimizasyon', 'insan_kaynak_planlama', 'makine_kaynak_planlama'],
    kapsam_siniri: ['kod_yazma', 'tasarim', 'test', 'deployment', 'veritabani', 'guvenlik', 'izleme', 'dokumantasyon'],
    durum: 'HAZIR', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'MK-04', kod_adi: 'MALİYET-DELTA', takim_kodu: 'MK', asama: A,
    uzmanlik_alani: 'Maliyet ve Kaynak',
    gorev_tanimi: 'Bütçe hesaplar, gerekli insan/makine kaynaklarını belirler',
    beceriler: ['maliyet_tahmini', 'kaynak_planlama', 'butce_yonetimi', 'roi_hesaplama', 'kaynak_dagitimi', 'maliyet_optimizasyon', 'insan_kaynak_planlama', 'makine_kaynak_planlama'],
    kapsam_siniri: ['kod_yazma', 'tasarim', 'test', 'deployment', 'veritabani', 'guvenlik', 'izleme', 'dokumantasyon'],
    durum: 'HAZIR', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'MK-05', kod_adi: 'MALİYET-ECHO', takim_kodu: 'MK', asama: A,
    uzmanlik_alani: 'Maliyet ve Kaynak',
    gorev_tanimi: 'Bütçe hesaplar, gerekli insan/makine kaynaklarını belirler',
    beceriler: ['maliyet_tahmini', 'kaynak_planlama', 'butce_yonetimi', 'roi_hesaplama', 'kaynak_dagitimi', 'maliyet_optimizasyon', 'insan_kaynak_planlama', 'makine_kaynak_planlama'],
    kapsam_siniri: ['kod_yazma', 'tasarim', 'test', 'deployment', 'veritabani', 'guvenlik', 'izleme', 'dokumantasyon'],
    durum: 'HAZIR', tamamlanan_gorev: 0, hata_sayisi: 0 },

  // ── ZP: ZAMAN PLANLAMASI ────────────────────────────────────
  { id: 'ZP-01', kod_adi: 'ZAMAN-ALFA', takim_kodu: 'ZP', asama: A,
    uzmanlik_alani: 'Zaman Planlaması',
    gorev_tanimi: 'Takvim çıkarır, bağımlılıkları belirler, kritik yolu tespit eder',
    beceriler: ['gantt_planlama', 'milestone_yonetimi', 'bagimlilik_yonetimi', 'kritik_yol_analizi', 'takvim_cikarma', 'sure_tahmini', 'gecikme_analizi', 'onceliklendirme'],
    kapsam_siniri: ['kod_yazma', 'tasarim', 'test', 'deployment', 'veritabani', 'guvenlik', 'izleme', 'dokumantasyon'],
    durum: 'HAZIR', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'ZP-02', kod_adi: 'ZAMAN-BRAVO', takim_kodu: 'ZP', asama: A,
    uzmanlik_alani: 'Zaman Planlaması',
    gorev_tanimi: 'Takvim çıkarır, bağımlılıkları belirler, kritik yolu tespit eder',
    beceriler: ['gantt_planlama', 'milestone_yonetimi', 'bagimlilik_yonetimi', 'kritik_yol_analizi', 'takvim_cikarma', 'sure_tahmini', 'gecikme_analizi', 'onceliklendirme'],
    kapsam_siniri: ['kod_yazma', 'tasarim', 'test', 'deployment', 'veritabani', 'guvenlik', 'izleme', 'dokumantasyon'],
    durum: 'HAZIR', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'ZP-03', kod_adi: 'ZAMAN-CHARLIE', takim_kodu: 'ZP', asama: A,
    uzmanlik_alani: 'Zaman Planlaması',
    gorev_tanimi: 'Takvim çıkarır, bağımlılıkları belirler, kritik yolu tespit eder',
    beceriler: ['gantt_planlama', 'milestone_yonetimi', 'bagimlilik_yonetimi', 'kritik_yol_analizi', 'takvim_cikarma', 'sure_tahmini', 'gecikme_analizi', 'onceliklendirme'],
    kapsam_siniri: ['kod_yazma', 'tasarim', 'test', 'deployment', 'veritabani', 'guvenlik', 'izleme', 'dokumantasyon'],
    durum: 'HAZIR', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'ZP-04', kod_adi: 'ZAMAN-DELTA', takim_kodu: 'ZP', asama: A,
    uzmanlik_alani: 'Zaman Planlaması',
    gorev_tanimi: 'Takvim çıkarır, bağımlılıkları belirler, kritik yolu tespit eder',
    beceriler: ['gantt_planlama', 'milestone_yonetimi', 'bagimlilik_yonetimi', 'kritik_yol_analizi', 'takvim_cikarma', 'sure_tahmini', 'gecikme_analizi', 'onceliklendirme'],
    kapsam_siniri: ['kod_yazma', 'tasarim', 'test', 'deployment', 'veritabani', 'guvenlik', 'izleme', 'dokumantasyon'],
    durum: 'HAZIR', tamamlanan_gorev: 0, hata_sayisi: 0 },
  { id: 'ZP-05', kod_adi: 'ZAMAN-ECHO', takim_kodu: 'ZP', asama: A,
    uzmanlik_alani: 'Zaman Planlaması',
    gorev_tanimi: 'Takvim çıkarır, bağımlılıkları belirler, kritik yolu tespit eder',
    beceriler: ['gantt_planlama', 'milestone_yonetimi', 'bagimlilik_yonetimi', 'kritik_yol_analizi', 'takvim_cikarma', 'sure_tahmini', 'gecikme_analizi', 'onceliklendirme'],
    kapsam_siniri: ['kod_yazma', 'tasarim', 'test', 'deployment', 'veritabani', 'guvenlik', 'izleme', 'dokumantasyon'],
    durum: 'HAZIR', tamamlanan_gorev: 0, hata_sayisi: 0 },
];

module.exports = { YAPIM_ONCESI };
